/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CreemCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { CreemError } from "../models/errors/creemerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";
import {
  createPageIterator,
  haltIterator,
  PageIterator,
  Paginator,
} from "../types/operations.js";

/**
 * Search discounts
 *
 * @remarks
 * Search and list discount codes for a store with filters and pagination.
 */
export function discountsSearch(
  client: CreemCore,
  pageNumber?: number | undefined,
  pageSize?: number | undefined,
  productId?: string | undefined,
  status?: operations.Status | undefined,
  type?: operations.Type | undefined,
  createdAfter?: string | undefined,
  createdBefore?: string | undefined,
  options?: RequestOptions,
): APIPromise<
  PageIterator<
    Result<
      operations.SearchDiscountsResponse,
      | CreemError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    { page: number }
  >
> {
  return new APIPromise($do(
    client,
    pageNumber,
    pageSize,
    productId,
    status,
    type,
    createdAfter,
    createdBefore,
    options,
  ));
}

async function $do(
  client: CreemCore,
  pageNumber?: number | undefined,
  pageSize?: number | undefined,
  productId?: string | undefined,
  status?: operations.Status | undefined,
  type?: operations.Type | undefined,
  createdAfter?: string | undefined,
  createdBefore?: string | undefined,
  options?: RequestOptions,
): Promise<
  [
    PageIterator<
      Result<
        operations.SearchDiscountsResponse,
        | CreemError
        | ResponseValidationError
        | ConnectionError
        | RequestAbortedError
        | RequestTimeoutError
        | InvalidRequestError
        | UnexpectedClientError
        | SDKValidationError
      >,
      { page: number }
    >,
    APICall,
  ]
> {
  const input: operations.SearchDiscountsRequest = {
    pageNumber: pageNumber,
    pageSize: pageSize,
    productId: productId,
    status: status,
    type: type,
    createdAfter: createdAfter,
    createdBefore: createdBefore,
  };

  const parsed = safeParse(
    input,
    (value) => operations.SearchDiscountsRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [haltIterator(parsed), { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const path = pathToFunc("/v1/discounts/search")();

  const query = encodeFormQuery({
    "created_after": payload.created_after,
    "created_before": payload.created_before,
    "page_number": payload.page_number,
    "page_size": payload.page_size,
    "product_id": payload.product_id,
    "status": payload.status,
    "type": payload.type,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKey);
  const securityInput = secConfig == null ? {} : { apiKey: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "searchDiscounts",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKey,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [haltIterator(requestRes), { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [haltIterator(doResult), { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result, raw] = await M.match<
    operations.SearchDiscountsResponse,
    | CreemError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.SearchDiscountsResponse$inboundSchema, {
      key: "Result",
    }),
    M.fail([400, 401, 404, "4XX"]),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [haltIterator(result), {
      status: "complete",
      request: req,
      response,
    }];
  }

  const nextFunc = (
    responseData: unknown,
  ): {
    next: Paginator<
      Result<
        operations.SearchDiscountsResponse,
        | CreemError
        | ResponseValidationError
        | ConnectionError
        | RequestAbortedError
        | RequestTimeoutError
        | InvalidRequestError
        | UnexpectedClientError
        | SDKValidationError
      >
    >;
    "~next"?: { page: number };
  } => {
    const page = input?.pageNumber ?? 1;
    const nextPage = page + 1;
    const numPages =
      (responseData as { pagination: { total_pages: unknown } }).pagination
        .total_pages;
    if (typeof numPages !== "number" || numPages <= page) {
      return { next: () => null };
    }

    if (!responseData) {
      return { next: () => null };
    }
    const results = (responseData as { items: unknown }).items;
    if (!Array.isArray(results) || !results.length) {
      return { next: () => null };
    }
    const limit = input?.pageSize ?? 10;
    if (results.length < limit) {
      return { next: () => null };
    }

    const nextVal = () =>
      discountsSearch(
        client,
        nextPage,
        pageSize,
        productId,
        status,
        type,
        createdAfter,
        createdBefore,
        options,
      );

    return { next: nextVal, "~next": { page: nextPage } };
  };

  const page = { ...result, ...nextFunc(raw) };
  return [{ ...page, ...createPageIterator(page, (v) => !v.ok) }, {
    status: "complete",
    request: req,
    response,
  }];
}
