import type { FunctionReference } from "convex/server";
import type { BillingSnapshot, RecurringCycle } from "../../core/types.js";

export type { CheckoutIntent } from "../../core/types.js";

/**
 * UI-side permission flags for billing widgets.
 * Controls which buttons are enabled/visible. This is **cosmetic gating only** —
 * enforce real permissions server-side in your Convex functions.
 *
 * When a permission is `false`, the corresponding button renders as disabled.
 * When omitted or `undefined`, all actions default to enabled.
 */
export type BillingPermissions = {
  /** Allow creating new checkouts (subscribe / buy buttons). */
  canCheckout?: boolean;
  /** Allow switching plans or billing intervals. */
  canChangeSubscription?: boolean;
  /** Allow cancelling the active subscription. */
  canCancelSubscription?: boolean;
  /** Allow resuming a paused or scheduled-cancel subscription. */
  canResumeSubscription?: boolean;
  /** Allow changing the seat count on seat-based plans. */
  canUpdateSeats?: boolean;
  /** Allow opening the Creem customer billing portal. */
  canAccessPortal?: boolean;
};

/**
 * Backend function references for connected billing widgets.
 * Created once in your layout/page and passed to `<Subscription.Root>`, `<Product.Root>`, and `<BillingPortal>`.
 *
 * All references point to Convex functions generated by `creem.api({ resolve })`
 * or your own custom wrappers.
 *
 * @example
 * ```ts
 * const billingApi: ConnectedBillingApi = {
 *   uiModel: api.billing.uiModel,
 *   checkouts: { create: api.billing.checkoutsCreate },
 *   subscriptions: {
 *     update: api.billing.subscriptionsUpdate,
 *     cancel: api.billing.subscriptionsCancel,
 *     resume: api.billing.subscriptionsResume,
 *   },
 *   customers: { portalUrl: api.billing.customersPortalUrl },
 * };
 * ```
 */
export type ConnectedBillingApi = {
  /** Query that returns the `ConnectedBillingModel` — called by all widgets to load billing state. */
  uiModel: FunctionReference<"query">;
  /** Checkout actions. */
  checkouts: {
    /** Create a checkout session and return `{ url }`. */
    create: FunctionReference<"action">;
  };
  /** Subscription mutation references. All optional — omit to hide the corresponding UI controls. */
  subscriptions?: {
    /** Plan switch or seat update mutation. */
    update?: FunctionReference<"mutation">;
    /** Cancel subscription mutation. */
    cancel?: FunctionReference<"mutation">;
    /** Resume paused/scheduled-cancel subscription mutation. */
    resume?: FunctionReference<"mutation">;
  };
  /** Customer actions. */
  customers?: {
    /** Action that returns `{ url }` for the Creem billing portal. */
    portalUrl?: FunctionReference<"action">;
  };
};

/** Product data as returned by the billing model query. Mirrors the Convex DB product schema. */
export type ConnectedProduct = {
  id: string;
  name?: string;
  description?: string;
  price?: number;
  currency?: string;
  billingType?: string;
  billingPeriod?: string;
  status?: string;
  taxMode?: string;
  taxCategory?: string;
  imageUrl?: string;
  features?: Array<{ id: string; description: string }>;
};

/**
 * Complete billing state returned by the `uiModel` query.
 * Consumed internally by all connected widgets — you typically don't need to access this directly.
 */
export type ConnectedBillingModel = {
  /** Authenticated user info, or `null` when unauthenticated (public pricing page). */
  user: {
    _id: string;
    email: string;
    isFree?: boolean;
    isTrialing?: boolean;
    trialEnd?: string | null;
  } | null;
  /** Resolved billing state (plan, status, available actions). `null` when unauthenticated. */
  billingSnapshot: BillingSnapshot | null;
  /** All synced products from the Creem dashboard. */
  allProducts: ConnectedProduct[];
  /** Product IDs the entity has purchased (one-time orders). */
  ownedProductIds: string[];
  /** Product ID of the current subscription, or `null`. */
  subscriptionProductId: string | null;
  /** All active subscriptions with full details. */
  activeSubscriptions?: Array<{
    id: string;
    productId: string;
    status: string;
    cancelAtPeriodEnd: boolean;
    currentPeriodEnd: string | null;
    currentPeriodStart: string;
    seats: number | null;
    recurringInterval: string | null;
    trialEnd?: string | null;
  }>;
  /** Whether this entity has a Creem customer record (needed for billing portal). */
  hasCreemCustomer?: boolean;
  /** Reserved for future billing policy data. */
  policy?: unknown;
};

/**
 * Plan type for `<Subscription.Item>`.
 * - `"free"` — free tier, no checkout
 * - `"single"` — standard paid plan (flat pricing)
 * - `"seat-based"` — per-seat pricing with optional seat picker
 * - `"enterprise"` — "Contact sales" CTA, no checkout
 */
export type SubscriptionPlanType =
  | "free"
  | "single"
  | "seat-based"
  | "enterprise";

export type SubscriptionPlanRegistration = {
  planId: string;
  type: SubscriptionPlanType;
  title?: string;
  description?: string;
  contactUrl?: string;
  recommended?: boolean;
  productIds?: Partial<Record<RecurringCycle, string>>;
};

/**
 * Product type for `<Product.Item>`.
 * - `"one-time"` — purchased once, shows "Owned" badge after purchase
 * - `"recurring"` — can be purchased multiple times (consumable), no "Owned" badge
 */
export type ProductType = "one-time" | "recurring";

/**
 * Upgrade path rule for `<Product.Root transition={[...]}>`.
 * - `"direct"` — checkout uses the target product directly
 * - `"via_product"` — checkout uses a dedicated upgrade product (delta pricing)
 */
export type Transition =
  | { from: string; to: string; kind: "direct" }
  | {
      from: string;
      to: string;
      kind: "via_product";
      /** Creem product ID for the upgrade (e.g. a delta-priced "Basic → Premium" product). */
      viaProductId: string;
    };

export type ProductItemRegistration = {
  productId: string;
  type: ProductType;
  title?: string;
  description?: string;
};
