/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customerCreditsCloseAccount } from "../funcs/customerCreditsCloseAccount.js";
import { customerCreditsCreateAccount } from "../funcs/customerCreditsCreateAccount.js";
import { customerCreditsCreditAccount } from "../funcs/customerCreditsCreditAccount.js";
import { customerCreditsDebitAccount } from "../funcs/customerCreditsDebitAccount.js";
import { customerCreditsFreezeAccount } from "../funcs/customerCreditsFreezeAccount.js";
import { customerCreditsGetAccount } from "../funcs/customerCreditsGetAccount.js";
import { customerCreditsGetAccountBalance } from "../funcs/customerCreditsGetAccountBalance.js";
import { customerCreditsListAccounts } from "../funcs/customerCreditsListAccounts.js";
import { customerCreditsListEntries } from "../funcs/customerCreditsListEntries.js";
import { customerCreditsReverseTransaction } from "../funcs/customerCreditsReverseTransaction.js";
import { customerCreditsUnfreezeAccount } from "../funcs/customerCreditsUnfreezeAccount.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class CustomerCredits extends ClientSDK {
  /**
   * Create a customer credits account
   *
   * @remarks
   * Create a new credits account for a customer. Optionally seed it with an initial balance.
   */
  async createAccount(
    request: components.CreateAccountDto,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(customerCreditsCreateAccount(
      this,
      request,
      options,
    ));
  }

  /**
   * List customer credits accounts
   *
   * @remarks
   * List accounts for the authenticated store with cursor pagination. System accounts are excluded.
   */
  async listAccounts(
    limit?: number | undefined,
    customerId?: string | undefined,
    startingAfter?: string | undefined,
    endingBefore?: string | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.ListCustomerCreditsAccountsResponse,
      { cursor: string }
    >
  > {
    return unwrapResultIterator(customerCreditsListAccounts(
      this,
      limit,
      customerId,
      startingAfter,
      endingBefore,
      options,
    ));
  }

  /**
   * Retrieve a customer credits account
   *
   * @remarks
   * Get details of a customer credits account by ID.
   */
  async getAccount(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(customerCreditsGetAccount(
      this,
      id,
      options,
    ));
  }

  /**
   * Get account balance
   *
   * @remarks
   * Get the current balance of an account. Optionally pass ?at= for historical balance.
   */
  async getAccountBalance(
    id: string,
    at?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.BalanceResponseDto> {
    return unwrapAsync(customerCreditsGetAccountBalance(
      this,
      id,
      at,
      options,
    ));
  }

  /**
   * List account entries
   *
   * @remarks
   * List the credit and debit history for an account with cursor pagination.
   */
  async listEntries(
    id: string,
    limit?: number | undefined,
    startingAfter?: string | undefined,
    endingBefore?: string | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.ListCustomerCreditsAccountEntriesResponse,
      { cursor: string }
    >
  > {
    return unwrapResultIterator(customerCreditsListEntries(
      this,
      id,
      limit,
      startingAfter,
      endingBefore,
      options,
    ));
  }

  /**
   * Freeze an account
   *
   * @remarks
   * Freeze an account to prevent new transactions.
   */
  async freezeAccount(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(customerCreditsFreezeAccount(
      this,
      id,
      options,
    ));
  }

  /**
   * Unfreeze an account
   *
   * @remarks
   * Unfreeze a frozen account to allow transactions again.
   */
  async unfreezeAccount(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(customerCreditsUnfreezeAccount(
      this,
      id,
      options,
    ));
  }

  /**
   * Credit an account
   *
   * @remarks
   * Add credits to a customer account. Returns the resulting transaction record.
   */
  async creditAccount(
    id: string,
    creditDebitRequestDto: components.CreditDebitRequestDto,
    options?: RequestOptions,
  ): Promise<components.TransactionResponseDto> {
    return unwrapAsync(customerCreditsCreditAccount(
      this,
      id,
      creditDebitRequestDto,
      options,
    ));
  }

  /**
   * Debit an account
   *
   * @remarks
   * Deduct credits from a customer account. Returns the resulting transaction record.
   */
  async debitAccount(
    id: string,
    creditDebitRequestDto: components.CreditDebitRequestDto,
    options?: RequestOptions,
  ): Promise<components.TransactionResponseDto> {
    return unwrapAsync(customerCreditsDebitAccount(
      this,
      id,
      creditDebitRequestDto,
      options,
    ));
  }

  /**
   * Reverse a transaction
   *
   * @remarks
   * Reverse a previous credit or debit on this account. Creates a new transaction that undoes the original, preserving the full history.
   */
  async reverseTransaction(
    id: string,
    reverseTransactionRequestDto: components.ReverseTransactionRequestDto,
    options?: RequestOptions,
  ): Promise<components.TransactionResponseDto> {
    return unwrapAsync(customerCreditsReverseTransaction(
      this,
      id,
      reverseTransactionRequestDto,
      options,
    ));
  }

  /**
   * Close an account
   *
   * @remarks
   * Permanently close an account. This action cannot be undone.
   */
  async closeAccount(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(customerCreditsCloseAccount(
      this,
      id,
      options,
    ));
  }
}
