/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreate } from "../funcs/customersCreate.js";
import { customersGenerateBillingLinks } from "../funcs/customersGenerateBillingLinks.js";
import { customersGetOrders } from "../funcs/customersGetOrders.js";
import { customersList } from "../funcs/customersList.js";
import { customersListLicenses } from "../funcs/customersListLicenses.js";
import { customersListSubscriptions } from "../funcs/customersListSubscriptions.js";
import { customersRetrieve } from "../funcs/customersRetrieve.js";
import { customersUpdate } from "../funcs/customersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Customers extends ClientSDK {
  /**
   * List all customers
   *
   * @remarks
   * Retrieve a paginated list of all customers. Filter and search through your customer base.
   */
  async list(
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListCustomersResponse, { page: number }>> {
    return unwrapResultIterator(customersList(
      this,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * List customer orders
   *
   * @remarks
   * Retrieve a paginated list of orders for a specific customer.
   */
  async getOrders(
    id: string,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.OrderListEntity> {
    return unwrapAsync(customersGetOrders(
      this,
      id,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * List customer subscriptions
   *
   * @remarks
   * Retrieve a paginated list of subscriptions for a specific customer.
   */
  async listSubscriptions(
    id: string,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.SubscriptionListEntity> {
    return unwrapAsync(customersListSubscriptions(
      this,
      id,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * List customer licenses
   *
   * @remarks
   * Retrieve a paginated list of license keys for a specific customer.
   */
  async listLicenses(
    id: string,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.LicenseListEntity> {
    return unwrapAsync(customersListLicenses(
      this,
      id,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * Retrieve a customer
   *
   * @remarks
   * Retrieve customer information by ID or email. View purchase history, subscriptions, and profile details.
   */
  async retrieve(
    customerId?: string | undefined,
    email?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.CustomerEntity> {
    return unwrapAsync(customersRetrieve(
      this,
      customerId,
      email,
      options,
    ));
  }

  /**
   * Create a customer
   *
   * @remarks
   * Create a new customer record for the authenticated store.
   */
  async create(
    request: components.CreateCustomerRequestEntity,
    options?: RequestOptions,
  ): Promise<components.CustomerEntity> {
    return unwrapAsync(customersCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a customer
   */
  async update(
    request: components.UpdateCustomerRequestEntity,
    options?: RequestOptions,
  ): Promise<components.CustomerEntity> {
    return unwrapAsync(customersUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate Customer Links
   *
   * @remarks
   * Generate a customer portal link for managing billing, subscriptions, and payment methods.
   */
  async generateBillingLinks(
    request: components.CreateCustomerPortalLinkRequestEntity,
    options?: RequestOptions,
  ): Promise<components.CustomerLinksEntity> {
    return unwrapAsync(customersGenerateBillingLinks(
      this,
      request,
      options,
    ));
  }
}
