/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { moderationScreenPrompt } from "../funcs/moderationScreenPrompt.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Moderation extends ClientSDK {
  /**
   * Screen a prompt
   *
   * @remarks
   * Evaluate a text prompt against content policies before generation. This endpoint is experimental and may change.
   */
  async screenPrompt(
    request: components.ScreenPromptRequest,
    options?: RequestOptions,
  ): Promise<components.ScreenPromptResponse> {
    return unwrapAsync(moderationScreenPrompt(
      this,
      request,
      options,
    ));
  }
}
