/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsArchive } from "../funcs/productsArchive.js";
import { productsCreate } from "../funcs/productsCreate.js";
import { productsGet } from "../funcs/productsGet.js";
import { productsGetById } from "../funcs/productsGetById.js";
import { productsSearch } from "../funcs/productsSearch.js";
import { productsUpdate } from "../funcs/productsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Products extends ClientSDK {
  /**
   * Retrieve a product
   *
   * @remarks
   * Retrieve product details by ID. View pricing, billing type, status, and product configuration.
   */
  async get(
    productId: string,
    options?: RequestOptions,
  ): Promise<components.ProductEntity> {
    return unwrapAsync(productsGet(
      this,
      productId,
      options,
    ));
  }

  /**
   * Creates a new product.
   *
   * @remarks
   * Create a new product for one-time payments, including free products with a 0 price, or subscriptions. Configure pricing, billing cycles, and features.
   */
  async create(
    request: components.CreateProductRequestEntity,
    options?: RequestOptions,
  ): Promise<components.ProductEntity> {
    return unwrapAsync(productsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List all products
   *
   * @remarks
   * Search and retrieve a paginated list of products. Filter by status, billing type, and other criteria.
   */
  async search(
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    status?: components.ProductStatus | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.SearchProductsResponse, { page: number }>
  > {
    return unwrapResultIterator(productsSearch(
      this,
      pageNumber,
      pageSize,
      status,
      options,
    ));
  }

  /**
   * Retrieve a product
   *
   * @remarks
   * Retrieve a single product by its ID.
   */
  async getById(
    id: string,
    options?: RequestOptions,
  ): Promise<components.ProductEntity> {
    return unwrapAsync(productsGetById(
      this,
      id,
      options,
    ));
  }

  /**
   * Update a product
   *
   * @remarks
   * Update a product. Only supplied fields change. Changing a price field mints a new default price; existing subscriptions keep the price they were purchased under.
   */
  async update(
    id: string,
    updateProductRequestEntity: components.UpdateProductRequestEntity,
    options?: RequestOptions,
  ): Promise<components.ProductEntity> {
    return unwrapAsync(productsUpdate(
      this,
      id,
      updateProductRequestEntity,
      options,
    ));
  }

  /**
   * Archive a product
   *
   * @remarks
   * Archive a product (soft-delete). The product is retained for historical orders and subscriptions but can no longer be purchased. Archived products remain retrievable and appear in list results when filtering by `status=archived`.
   */
  async archive(
    id: string,
    options?: RequestOptions,
  ): Promise<components.ProductEntity> {
    return unwrapAsync(productsArchive(
      this,
      id,
      options,
    ));
  }
}
