/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Checkouts } from "./checkouts.js";
import { CustomerCredits } from "./customercredits.js";
import { Customers } from "./customers.js";
import { Discounts } from "./discounts.js";
import { Licenses } from "./licenses.js";
import { Moderation } from "./moderation.js";
import { Products } from "./products.js";
import { Stats } from "./stats.js";
import { Subscriptions } from "./subscriptions.js";
import { Transactions } from "./transactions.js";

export class Creem extends ClientSDK {
  private _products?: Products;
  get products(): Products {
    return (this._products ??= new Products(this._options));
  }

  private _customers?: Customers;
  get customers(): Customers {
    return (this._customers ??= new Customers(this._options));
  }

  private _subscriptions?: Subscriptions;
  get subscriptions(): Subscriptions {
    return (this._subscriptions ??= new Subscriptions(this._options));
  }

  private _checkouts?: Checkouts;
  get checkouts(): Checkouts {
    return (this._checkouts ??= new Checkouts(this._options));
  }

  private _licenses?: Licenses;
  get licenses(): Licenses {
    return (this._licenses ??= new Licenses(this._options));
  }

  private _discounts?: Discounts;
  get discounts(): Discounts {
    return (this._discounts ??= new Discounts(this._options));
  }

  private _transactions?: Transactions;
  get transactions(): Transactions {
    return (this._transactions ??= new Transactions(this._options));
  }

  private _stats?: Stats;
  get stats(): Stats {
    return (this._stats ??= new Stats(this._options));
  }

  private _moderation?: Moderation;
  get moderation(): Moderation {
    return (this._moderation ??= new Moderation(this._options));
  }

  private _customerCredits?: CustomerCredits;
  get customerCredits(): CustomerCredits {
    return (this._customerCredits ??= new CustomerCredits(this._options));
  }
}
