/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statsGetSummary } from "../funcs/statsGetSummary.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Stats extends ClientSDK {
  /**
   * Get store metrics summary
   *
   * @remarks
   * Retrieve aggregated store metrics including counts, revenue, and MRR. When startDate and endDate are provided, totals are filtered to that date range. When interval is also provided, the response includes a periods array with time-series data points grouped by that interval. The periods array starts from the store's first transaction or startDate, whichever is later, to avoid empty leading buckets. All monetary amounts are in cents (integer, no decimals).
   */
  async getSummary(
    currency: operations.Currency,
    startDate?: number | undefined,
    endDate?: number | undefined,
    interval?: operations.Interval | undefined,
    options?: RequestOptions,
  ): Promise<components.StatsSummaryEntity> {
    return unwrapAsync(statsGetSummary(
      this,
      currency,
      startDate,
      endDate,
      interval,
      options,
    ));
  }
}
