/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ArchiveProductRequest = {
  /**
   * The product ID
   */
  id: string;
};

/** @internal */
export const ArchiveProductRequest$inboundSchema: z.ZodType<
  ArchiveProductRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type ArchiveProductRequest$Outbound = {
  id: string;
};

/** @internal */
export const ArchiveProductRequest$outboundSchema: z.ZodType<
  ArchiveProductRequest$Outbound,
  z.ZodTypeDef,
  ArchiveProductRequest
> = z.object({
  id: z.string(),
});

export function archiveProductRequestToJSON(
  archiveProductRequest: ArchiveProductRequest,
): string {
  return JSON.stringify(
    ArchiveProductRequest$outboundSchema.parse(archiveProductRequest),
  );
}
export function archiveProductRequestFromJSON(
  jsonString: string,
): SafeParseResult<ArchiveProductRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArchiveProductRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArchiveProductRequest' from JSON`,
  );
}
