/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CloseCustomerCreditsAccountRequest = {
  id: string;
};

/** @internal */
export const CloseCustomerCreditsAccountRequest$inboundSchema: z.ZodType<
  CloseCustomerCreditsAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type CloseCustomerCreditsAccountRequest$Outbound = {
  id: string;
};

/** @internal */
export const CloseCustomerCreditsAccountRequest$outboundSchema: z.ZodType<
  CloseCustomerCreditsAccountRequest$Outbound,
  z.ZodTypeDef,
  CloseCustomerCreditsAccountRequest
> = z.object({
  id: z.string(),
});

export function closeCustomerCreditsAccountRequestToJSON(
  closeCustomerCreditsAccountRequest: CloseCustomerCreditsAccountRequest,
): string {
  return JSON.stringify(
    CloseCustomerCreditsAccountRequest$outboundSchema.parse(
      closeCustomerCreditsAccountRequest,
    ),
  );
}
export function closeCustomerCreditsAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<CloseCustomerCreditsAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CloseCustomerCreditsAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CloseCustomerCreditsAccountRequest' from JSON`,
  );
}
