/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreditCustomerCreditsAccountRequest = {
  id: string;
  creditDebitRequestDto: components.CreditDebitRequestDto;
};

/** @internal */
export const CreditCustomerCreditsAccountRequest$inboundSchema: z.ZodType<
  CreditCustomerCreditsAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  CreditDebitRequestDto: components.CreditDebitRequestDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "CreditDebitRequestDto": "creditDebitRequestDto",
  });
});
/** @internal */
export type CreditCustomerCreditsAccountRequest$Outbound = {
  id: string;
  CreditDebitRequestDto: components.CreditDebitRequestDto$Outbound;
};

/** @internal */
export const CreditCustomerCreditsAccountRequest$outboundSchema: z.ZodType<
  CreditCustomerCreditsAccountRequest$Outbound,
  z.ZodTypeDef,
  CreditCustomerCreditsAccountRequest
> = z.object({
  id: z.string(),
  creditDebitRequestDto: components.CreditDebitRequestDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    creditDebitRequestDto: "CreditDebitRequestDto",
  });
});

export function creditCustomerCreditsAccountRequestToJSON(
  creditCustomerCreditsAccountRequest: CreditCustomerCreditsAccountRequest,
): string {
  return JSON.stringify(
    CreditCustomerCreditsAccountRequest$outboundSchema.parse(
      creditCustomerCreditsAccountRequest,
    ),
  );
}
export function creditCustomerCreditsAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreditCustomerCreditsAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreditCustomerCreditsAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditCustomerCreditsAccountRequest' from JSON`,
  );
}
