/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FreezeCustomerCreditsAccountRequest = {
  id: string;
};

/** @internal */
export const FreezeCustomerCreditsAccountRequest$inboundSchema: z.ZodType<
  FreezeCustomerCreditsAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type FreezeCustomerCreditsAccountRequest$Outbound = {
  id: string;
};

/** @internal */
export const FreezeCustomerCreditsAccountRequest$outboundSchema: z.ZodType<
  FreezeCustomerCreditsAccountRequest$Outbound,
  z.ZodTypeDef,
  FreezeCustomerCreditsAccountRequest
> = z.object({
  id: z.string(),
});

export function freezeCustomerCreditsAccountRequestToJSON(
  freezeCustomerCreditsAccountRequest: FreezeCustomerCreditsAccountRequest,
): string {
  return JSON.stringify(
    FreezeCustomerCreditsAccountRequest$outboundSchema.parse(
      freezeCustomerCreditsAccountRequest,
    ),
  );
}
export function freezeCustomerCreditsAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<FreezeCustomerCreditsAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FreezeCustomerCreditsAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FreezeCustomerCreditsAccountRequest' from JSON`,
  );
}
