/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCustomerCreditsAccountRequest = {
  id: string;
};

/** @internal */
export const GetCustomerCreditsAccountRequest$inboundSchema: z.ZodType<
  GetCustomerCreditsAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetCustomerCreditsAccountRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomerCreditsAccountRequest$outboundSchema: z.ZodType<
  GetCustomerCreditsAccountRequest$Outbound,
  z.ZodTypeDef,
  GetCustomerCreditsAccountRequest
> = z.object({
  id: z.string(),
});

export function getCustomerCreditsAccountRequestToJSON(
  getCustomerCreditsAccountRequest: GetCustomerCreditsAccountRequest,
): string {
  return JSON.stringify(
    GetCustomerCreditsAccountRequest$outboundSchema.parse(
      getCustomerCreditsAccountRequest,
    ),
  );
}
export function getCustomerCreditsAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerCreditsAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerCreditsAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerCreditsAccountRequest' from JSON`,
  );
}
