/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCustomerCreditsAccountBalanceRequest = {
  id: string;
  /**
   * ISO 8601 date. If present, computes balance at that point in time. If absent, returns O(1) projected balance.
   */
  at?: string | undefined;
};

/** @internal */
export const GetCustomerCreditsAccountBalanceRequest$inboundSchema: z.ZodType<
  GetCustomerCreditsAccountBalanceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  at: z.string().optional(),
});
/** @internal */
export type GetCustomerCreditsAccountBalanceRequest$Outbound = {
  id: string;
  at?: string | undefined;
};

/** @internal */
export const GetCustomerCreditsAccountBalanceRequest$outboundSchema: z.ZodType<
  GetCustomerCreditsAccountBalanceRequest$Outbound,
  z.ZodTypeDef,
  GetCustomerCreditsAccountBalanceRequest
> = z.object({
  id: z.string(),
  at: z.string().optional(),
});

export function getCustomerCreditsAccountBalanceRequestToJSON(
  getCustomerCreditsAccountBalanceRequest:
    GetCustomerCreditsAccountBalanceRequest,
): string {
  return JSON.stringify(
    GetCustomerCreditsAccountBalanceRequest$outboundSchema.parse(
      getCustomerCreditsAccountBalanceRequest,
    ),
  );
}
export function getCustomerCreditsAccountBalanceRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetCustomerCreditsAccountBalanceRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetCustomerCreditsAccountBalanceRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetCustomerCreditsAccountBalanceRequest' from JSON`,
  );
}
