/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetProductRequest = {
  /**
   * The product ID
   */
  id: string;
};

/** @internal */
export const GetProductRequest$inboundSchema: z.ZodType<
  GetProductRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetProductRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetProductRequest$outboundSchema: z.ZodType<
  GetProductRequest$Outbound,
  z.ZodTypeDef,
  GetProductRequest
> = z.object({
  id: z.string(),
});

export function getProductRequestToJSON(
  getProductRequest: GetProductRequest,
): string {
  return JSON.stringify(
    GetProductRequest$outboundSchema.parse(getProductRequest),
  );
}
export function getProductRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetProductRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductRequest' from JSON`,
  );
}
