/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListCustomerOrdersRequest = {
  /**
   * The unique identifier of the customer
   */
  id: string;
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListCustomerOrdersRequest$inboundSchema: z.ZodType<
  ListCustomerOrdersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  page_number: z.number().default(1),
  page_size: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
  });
});
/** @internal */
export type ListCustomerOrdersRequest$Outbound = {
  id: string;
  page_number: number;
  page_size: number;
};

/** @internal */
export const ListCustomerOrdersRequest$outboundSchema: z.ZodType<
  ListCustomerOrdersRequest$Outbound,
  z.ZodTypeDef,
  ListCustomerOrdersRequest
> = z.object({
  id: z.string(),
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
  });
});

export function listCustomerOrdersRequestToJSON(
  listCustomerOrdersRequest: ListCustomerOrdersRequest,
): string {
  return JSON.stringify(
    ListCustomerOrdersRequest$outboundSchema.parse(listCustomerOrdersRequest),
  );
}
export function listCustomerOrdersRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomerOrdersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCustomerOrdersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomerOrdersRequest' from JSON`,
  );
}
