/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListCustomerCreditsAccountsRequest = {
  /**
   * Maximum number of accounts to return
   */
  limit?: number | undefined;
  /**
   * Filter by owner ID (e.g. customer ID)
   */
  customerId?: string | undefined;
  /**
   * Cursor for forward pagination — account ID to start after
   */
  startingAfter?: string | undefined;
  /**
   * Cursor for backward pagination — account ID to end before
   */
  endingBefore?: string | undefined;
};

export type ListCustomerCreditsAccountsResponse = {
  result: components.AccountListResponseDto;
};

/** @internal */
export const ListCustomerCreditsAccountsRequest$inboundSchema: z.ZodType<
  ListCustomerCreditsAccountsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().default(10),
  customer_id: z.string().optional(),
  starting_after: z.string().optional(),
  ending_before: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "starting_after": "startingAfter",
    "ending_before": "endingBefore",
  });
});
/** @internal */
export type ListCustomerCreditsAccountsRequest$Outbound = {
  limit: number;
  customer_id?: string | undefined;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
};

/** @internal */
export const ListCustomerCreditsAccountsRequest$outboundSchema: z.ZodType<
  ListCustomerCreditsAccountsRequest$Outbound,
  z.ZodTypeDef,
  ListCustomerCreditsAccountsRequest
> = z.object({
  limit: z.number().default(10),
  customerId: z.string().optional(),
  startingAfter: z.string().optional(),
  endingBefore: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    startingAfter: "starting_after",
    endingBefore: "ending_before",
  });
});

export function listCustomerCreditsAccountsRequestToJSON(
  listCustomerCreditsAccountsRequest: ListCustomerCreditsAccountsRequest,
): string {
  return JSON.stringify(
    ListCustomerCreditsAccountsRequest$outboundSchema.parse(
      listCustomerCreditsAccountsRequest,
    ),
  );
}
export function listCustomerCreditsAccountsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomerCreditsAccountsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListCustomerCreditsAccountsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomerCreditsAccountsRequest' from JSON`,
  );
}

/** @internal */
export const ListCustomerCreditsAccountsResponse$inboundSchema: z.ZodType<
  ListCustomerCreditsAccountsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.AccountListResponseDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListCustomerCreditsAccountsResponse$Outbound = {
  Result: components.AccountListResponseDto$Outbound;
};

/** @internal */
export const ListCustomerCreditsAccountsResponse$outboundSchema: z.ZodType<
  ListCustomerCreditsAccountsResponse$Outbound,
  z.ZodTypeDef,
  ListCustomerCreditsAccountsResponse
> = z.object({
  result: components.AccountListResponseDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listCustomerCreditsAccountsResponseToJSON(
  listCustomerCreditsAccountsResponse: ListCustomerCreditsAccountsResponse,
): string {
  return JSON.stringify(
    ListCustomerCreditsAccountsResponse$outboundSchema.parse(
      listCustomerCreditsAccountsResponse,
    ),
  );
}
export function listCustomerCreditsAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomerCreditsAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListCustomerCreditsAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomerCreditsAccountsResponse' from JSON`,
  );
}
