/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListCustomerLicensesRequest = {
  /**
   * The unique identifier of the customer
   */
  id: string;
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListCustomerLicensesRequest$inboundSchema: z.ZodType<
  ListCustomerLicensesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  page_number: z.number().default(1),
  page_size: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
  });
});
/** @internal */
export type ListCustomerLicensesRequest$Outbound = {
  id: string;
  page_number: number;
  page_size: number;
};

/** @internal */
export const ListCustomerLicensesRequest$outboundSchema: z.ZodType<
  ListCustomerLicensesRequest$Outbound,
  z.ZodTypeDef,
  ListCustomerLicensesRequest
> = z.object({
  id: z.string(),
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
  });
});

export function listCustomerLicensesRequestToJSON(
  listCustomerLicensesRequest: ListCustomerLicensesRequest,
): string {
  return JSON.stringify(
    ListCustomerLicensesRequest$outboundSchema.parse(
      listCustomerLicensesRequest,
    ),
  );
}
export function listCustomerLicensesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomerLicensesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCustomerLicensesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomerLicensesRequest' from JSON`,
  );
}
