/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ReverseCustomerCreditsAccountTransactionRequest = {
  id: string;
  reverseTransactionRequestDto: components.ReverseTransactionRequestDto;
};

/** @internal */
export const ReverseCustomerCreditsAccountTransactionRequest$inboundSchema:
  z.ZodType<
    ReverseCustomerCreditsAccountTransactionRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    ReverseTransactionRequestDto:
      components.ReverseTransactionRequestDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "ReverseTransactionRequestDto": "reverseTransactionRequestDto",
    });
  });
/** @internal */
export type ReverseCustomerCreditsAccountTransactionRequest$Outbound = {
  id: string;
  ReverseTransactionRequestDto:
    components.ReverseTransactionRequestDto$Outbound;
};

/** @internal */
export const ReverseCustomerCreditsAccountTransactionRequest$outboundSchema:
  z.ZodType<
    ReverseCustomerCreditsAccountTransactionRequest$Outbound,
    z.ZodTypeDef,
    ReverseCustomerCreditsAccountTransactionRequest
  > = z.object({
    id: z.string(),
    reverseTransactionRequestDto:
      components.ReverseTransactionRequestDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      reverseTransactionRequestDto: "ReverseTransactionRequestDto",
    });
  });

export function reverseCustomerCreditsAccountTransactionRequestToJSON(
  reverseCustomerCreditsAccountTransactionRequest:
    ReverseCustomerCreditsAccountTransactionRequest,
): string {
  return JSON.stringify(
    ReverseCustomerCreditsAccountTransactionRequest$outboundSchema.parse(
      reverseCustomerCreditsAccountTransactionRequest,
    ),
  );
}
export function reverseCustomerCreditsAccountTransactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ReverseCustomerCreditsAccountTransactionRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ReverseCustomerCreditsAccountTransactionRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ReverseCustomerCreditsAccountTransactionRequest' from JSON`,
  );
}
