/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Filter by discount status.
 */
export const Status = {
  Active: "active",
  Deleted: "deleted",
} as const;
/**
 * Filter by discount status.
 */
export type Status = ClosedEnum<typeof Status>;

/**
 * Filter by discount type.
 */
export const Type = {
  Percentage: "percentage",
  Fixed: "fixed",
} as const;
/**
 * Filter by discount type.
 */
export type Type = ClosedEnum<typeof Type>;

export type SearchDiscountsRequest = {
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
  /**
   * Filter discounts that apply to a specific product.
   */
  productId?: string | undefined;
  /**
   * Filter by discount status.
   */
  status?: Status | undefined;
  /**
   * Filter by discount type.
   */
  type?: Type | undefined;
  /**
   * Filter discounts created after this date.
   */
  createdAfter?: string | undefined;
  /**
   * Filter discounts created before this date.
   */
  createdBefore?: string | undefined;
};

export type SearchDiscountsResponse = {
  result: components.DiscountListEntity;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);
/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);
/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> =
  Type$inboundSchema;

/** @internal */
export const SearchDiscountsRequest$inboundSchema: z.ZodType<
  SearchDiscountsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_number: z.number().default(1),
  page_size: z.number().default(10),
  product_id: z.string().optional(),
  status: Status$inboundSchema.optional(),
  type: Type$inboundSchema.optional(),
  created_after: z.string().optional(),
  created_before: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
    "product_id": "productId",
    "created_after": "createdAfter",
    "created_before": "createdBefore",
  });
});
/** @internal */
export type SearchDiscountsRequest$Outbound = {
  page_number: number;
  page_size: number;
  product_id?: string | undefined;
  status?: string | undefined;
  type?: string | undefined;
  created_after?: string | undefined;
  created_before?: string | undefined;
};

/** @internal */
export const SearchDiscountsRequest$outboundSchema: z.ZodType<
  SearchDiscountsRequest$Outbound,
  z.ZodTypeDef,
  SearchDiscountsRequest
> = z.object({
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
  productId: z.string().optional(),
  status: Status$outboundSchema.optional(),
  type: Type$outboundSchema.optional(),
  createdAfter: z.string().optional(),
  createdBefore: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
    productId: "product_id",
    createdAfter: "created_after",
    createdBefore: "created_before",
  });
});

export function searchDiscountsRequestToJSON(
  searchDiscountsRequest: SearchDiscountsRequest,
): string {
  return JSON.stringify(
    SearchDiscountsRequest$outboundSchema.parse(searchDiscountsRequest),
  );
}
export function searchDiscountsRequestFromJSON(
  jsonString: string,
): SafeParseResult<SearchDiscountsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDiscountsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDiscountsRequest' from JSON`,
  );
}

/** @internal */
export const SearchDiscountsResponse$inboundSchema: z.ZodType<
  SearchDiscountsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.DiscountListEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type SearchDiscountsResponse$Outbound = {
  Result: components.DiscountListEntity$Outbound;
};

/** @internal */
export const SearchDiscountsResponse$outboundSchema: z.ZodType<
  SearchDiscountsResponse$Outbound,
  z.ZodTypeDef,
  SearchDiscountsResponse
> = z.object({
  result: components.DiscountListEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function searchDiscountsResponseToJSON(
  searchDiscountsResponse: SearchDiscountsResponse,
): string {
  return JSON.stringify(
    SearchDiscountsResponse$outboundSchema.parse(searchDiscountsResponse),
  );
}
export function searchDiscountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchDiscountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDiscountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDiscountsResponse' from JSON`,
  );
}
