/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SearchProductsRequest = {
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
  /**
   * Filter products by lifecycle status. Omit to return products of any status. `active` returns only non-archived products (the common case for catalogues and pricing pages); `archived` returns only archived products (useful for configuration synchronization).
   */
  status?: components.ProductStatus | undefined;
};

export type SearchProductsResponse = {
  result: components.ProductListEntity;
};

/** @internal */
export const SearchProductsRequest$inboundSchema: z.ZodType<
  SearchProductsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_number: z.number().default(1),
  page_size: z.number().default(10),
  status: components.ProductStatus$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
  });
});
/** @internal */
export type SearchProductsRequest$Outbound = {
  page_number: number;
  page_size: number;
  status?: string | undefined;
};

/** @internal */
export const SearchProductsRequest$outboundSchema: z.ZodType<
  SearchProductsRequest$Outbound,
  z.ZodTypeDef,
  SearchProductsRequest
> = z.object({
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
  status: components.ProductStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
  });
});

export function searchProductsRequestToJSON(
  searchProductsRequest: SearchProductsRequest,
): string {
  return JSON.stringify(
    SearchProductsRequest$outboundSchema.parse(searchProductsRequest),
  );
}
export function searchProductsRequestFromJSON(
  jsonString: string,
): SafeParseResult<SearchProductsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchProductsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchProductsRequest' from JSON`,
  );
}

/** @internal */
export const SearchProductsResponse$inboundSchema: z.ZodType<
  SearchProductsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.ProductListEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type SearchProductsResponse$Outbound = {
  Result: components.ProductListEntity$Outbound;
};

/** @internal */
export const SearchProductsResponse$outboundSchema: z.ZodType<
  SearchProductsResponse$Outbound,
  z.ZodTypeDef,
  SearchProductsResponse
> = z.object({
  result: components.ProductListEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function searchProductsResponseToJSON(
  searchProductsResponse: SearchProductsResponse,
): string {
  return JSON.stringify(
    SearchProductsResponse$outboundSchema.parse(searchProductsResponse),
  );
}
export function searchProductsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchProductsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchProductsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchProductsResponse' from JSON`,
  );
}
