/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UnfreezeCustomerCreditsAccountRequest = {
  id: string;
};

/** @internal */
export const UnfreezeCustomerCreditsAccountRequest$inboundSchema: z.ZodType<
  UnfreezeCustomerCreditsAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type UnfreezeCustomerCreditsAccountRequest$Outbound = {
  id: string;
};

/** @internal */
export const UnfreezeCustomerCreditsAccountRequest$outboundSchema: z.ZodType<
  UnfreezeCustomerCreditsAccountRequest$Outbound,
  z.ZodTypeDef,
  UnfreezeCustomerCreditsAccountRequest
> = z.object({
  id: z.string(),
});

export function unfreezeCustomerCreditsAccountRequestToJSON(
  unfreezeCustomerCreditsAccountRequest: UnfreezeCustomerCreditsAccountRequest,
): string {
  return JSON.stringify(
    UnfreezeCustomerCreditsAccountRequest$outboundSchema.parse(
      unfreezeCustomerCreditsAccountRequest,
    ),
  );
}
export function unfreezeCustomerCreditsAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<UnfreezeCustomerCreditsAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UnfreezeCustomerCreditsAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnfreezeCustomerCreditsAccountRequest' from JSON`,
  );
}
