/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateProductRequest = {
  /**
   * The product ID
   */
  id: string;
  updateProductRequestEntity: components.UpdateProductRequestEntity;
};

/** @internal */
export const UpdateProductRequest$inboundSchema: z.ZodType<
  UpdateProductRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  UpdateProductRequestEntity:
    components.UpdateProductRequestEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateProductRequestEntity": "updateProductRequestEntity",
  });
});
/** @internal */
export type UpdateProductRequest$Outbound = {
  id: string;
  UpdateProductRequestEntity: components.UpdateProductRequestEntity$Outbound;
};

/** @internal */
export const UpdateProductRequest$outboundSchema: z.ZodType<
  UpdateProductRequest$Outbound,
  z.ZodTypeDef,
  UpdateProductRequest
> = z.object({
  id: z.string(),
  updateProductRequestEntity:
    components.UpdateProductRequestEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateProductRequestEntity: "UpdateProductRequestEntity",
  });
});

export function updateProductRequestToJSON(
  updateProductRequest: UpdateProductRequest,
): string {
  return JSON.stringify(
    UpdateProductRequest$outboundSchema.parse(updateProductRequest),
  );
}
export function updateProductRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProductRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProductRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProductRequest' from JSON`,
  );
}
