/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customersListLicenses } from "../../funcs/customersListLicenses.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
};

export const tool$customersListLicenses: ToolDefinition<typeof args> = {
  name: "customers-list-licenses",
  description: `List customer licenses

Retrieve a paginated list of license keys for a specific customer.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersListLicenses(
      client,
      args.id,
      args.pageNumber,
      args.pageSize,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
