/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsGetAccountBalance } from "../../funcs/customerCreditsGetAccountBalance.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  at: z.string().optional(),
};

export const tool$customerCreditsGetAccountBalance: ToolDefinition<
  typeof args
> = {
  name: "customer-credits-get-account-balance",
  description: `Get account balance

Get the current balance of an account. Optionally pass ?at= for historical balance.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customerCreditsGetAccountBalance(
      client,
      args.id,
      args.at,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
