/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customerCreditsCreateAccount } from "../../funcs/customerCreditsCreateAccount.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateAccountDto$inboundSchema,
};

export const tool$customerCreditsCreateAccount: ToolDefinition<typeof args> = {
  name: "customer-credits-create-account",
  description: `Create a customer credits account

Create a new credits account for a customer. Optionally seed it with an initial balance.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customerCreditsCreateAccount(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
