/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsGetAccount } from "../../funcs/customerCreditsGetAccount.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$customerCreditsGetAccount: ToolDefinition<typeof args> = {
  name: "customer-credits-get-account",
  description: `Retrieve a customer credits account

Get details of a customer credits account by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customerCreditsGetAccount(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
