/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsFreezeAccount } from "../../funcs/customerCreditsFreezeAccount.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$customerCreditsFreezeAccount: ToolDefinition<typeof args> = {
  name: "customer-credits-freeze-account",
  description: `Freeze an account

Freeze an account to prevent new transactions.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customerCreditsFreezeAccount(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
