/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsUnfreezeAccount } from "../../funcs/customerCreditsUnfreezeAccount.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$customerCreditsUnfreezeAccount: ToolDefinition<typeof args> =
  {
    name: "customer-credits-unfreeze-account",
    description: `Unfreeze an account

Unfreeze a frozen account to allow transactions again.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await customerCreditsUnfreezeAccount(
        client,
        args.id,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
