/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { discountsSearch } from "../../funcs/discountsSearch.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
  productId: z.string().optional(),
  status: operations.Status$inboundSchema.optional(),
  type: operations.Type$inboundSchema.optional(),
  createdAfter: z.string().optional(),
  createdBefore: z.string().optional(),
};

export const tool$discountsSearch: ToolDefinition<typeof args> = {
  name: "discounts-search",
  description: `Search discounts

Search and list discount codes for a store with filters and pagination.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await discountsSearch(
      client,
      args.pageNumber,
      args.pageSize,
      args.productId,
      args.status,
      args.type,
      args.createdAfter,
      args.createdBefore,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
