/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { subscriptionsSearch } from "../../funcs/subscriptionsSearch.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
};

export const tool$subscriptionsSearch: ToolDefinition<typeof args> = {
  name: "subscriptions-search",
  description: `List all subscriptions

Search and retrieve a paginated list of subscriptions. View status, billing cycle, and customer info.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionsSearch(
      client,
      args.pageNumber,
      args.pageSize,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
