import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, it, expect, vi, beforeEach } from "vitest";
import { createMCPServer } from "../../src/mcp-server/server.js";
import { TEST_API_KEY, TEST_SERVER } from "../fixtures/testValues.js";
import type { ConsoleLogger } from "../../src/mcp-server/console-logger.js";

// The MCP tool list is generated by Speakeasy and grows with each new endpoint.
// Read the import count from server.ts so the assertion stays in sync without
// manual updates on every regen.
const serverSourcePath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../src/mcp-server/server.ts",
);
const EXPECTED_TOOL_COUNT = (
  readFileSync(serverSourcePath, "utf8").match(/^import\s+\{\s+tool\$/gm) ?? []
).length;

// Mock logger that matches ConsoleLogger interface
const createMockLogger = (): ConsoleLogger => ({
  debug: vi.fn(),
  info: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
});

describe("MCP Server", () => {
  let mockLogger: ConsoleLogger;

  beforeEach(() => {
    mockLogger = createMockLogger();
    vi.clearAllMocks();
  });

  it("should create MCP server instance", () => {
    const server = createMCPServer({
      logger: mockLogger,
      apiKey: TEST_API_KEY,
      server: TEST_SERVER,
    });

    expect(server).toBeDefined();
  });

  it("should register tools when created", () => {
    createMCPServer({
      logger: mockLogger,
      apiKey: TEST_API_KEY,
      server: TEST_SERVER,
    });

    // Verify tools were registered via logger debug calls
    expect(mockLogger.debug).toHaveBeenCalled();
  });

  it("should register expected number of tools", () => {
    createMCPServer({
      logger: mockLogger,
      apiKey: TEST_API_KEY,
      server: TEST_SERVER,
    });

    // Count the number of "Registered tool" debug calls
    const debugCalls = vi.mocked(mockLogger.debug).mock.calls;
    const toolRegistrationCalls = debugCalls.filter(
      (call) => call[0] === "Registered tool"
    );

    // Every `tool$xxx` import in server.ts must end up registered.
    expect(toolRegistrationCalls.length).toBe(EXPECTED_TOOL_COUNT);
  });

  it("should create server with custom server URL", () => {
    const customServerURL = "https://custom-api.creem.io";

    const server = createMCPServer({
      logger: mockLogger,
      apiKey: TEST_API_KEY,
      serverURL: customServerURL,
    });

    expect(server).toBeDefined();
  });

  it("should filter tools when allowedTools is provided", () => {
    createMCPServer({
      logger: mockLogger,
      apiKey: TEST_API_KEY,
      server: TEST_SERVER,
      allowedTools: ["products-get", "products-search"],
    });

    // Only allowed tools should be registered
    const debugCalls = vi.mocked(mockLogger.debug).mock.calls;
    const toolRegistrationCalls = debugCalls.filter(
      (call) => call[0] === "Registered tool"
    );

    expect(toolRegistrationCalls.length).toBe(2);
  });

  it("should create server without API key (will fail at runtime)", () => {
    // Server can be created without API key, but API calls will fail
    const server = createMCPServer({
      logger: mockLogger,
      server: TEST_SERVER,
    });

    expect(server).toBeDefined();
  });
});
