/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the creem SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx productsGet.example.ts
 */

import { Creem } from "creem";

const creem = new Creem({
  apiKey: process.env["CREEM_API_KEY"] ?? "",
});

async function main() {
  const result = await creem.products.get("prod_1234567890");

  console.log(result);
}

main().catch(console.error);
