/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccountResponseDto,
  AccountResponseDto$inboundSchema,
  AccountResponseDto$Outbound,
  AccountResponseDto$outboundSchema,
} from "./accountresponsedto.js";

export type AccountListResponseDto = {
  /**
   * Object type
   */
  object: string;
  /**
   * Array of accounts
   */
  data: Array<AccountResponseDto>;
  /**
   * Whether more items exist beyond this page
   */
  hasMore: boolean;
};

/** @internal */
export const AccountListResponseDto$inboundSchema: z.ZodType<
  AccountListResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string(),
  data: z.array(AccountResponseDto$inboundSchema),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});
/** @internal */
export type AccountListResponseDto$Outbound = {
  object: string;
  data: Array<AccountResponseDto$Outbound>;
  has_more: boolean;
};

/** @internal */
export const AccountListResponseDto$outboundSchema: z.ZodType<
  AccountListResponseDto$Outbound,
  z.ZodTypeDef,
  AccountListResponseDto
> = z.object({
  object: z.string(),
  data: z.array(AccountResponseDto$outboundSchema),
  hasMore: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
  });
});

export function accountListResponseDtoToJSON(
  accountListResponseDto: AccountListResponseDto,
): string {
  return JSON.stringify(
    AccountListResponseDto$outboundSchema.parse(accountListResponseDto),
  );
}
export function accountListResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<AccountListResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountListResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountListResponseDto' from JSON`,
  );
}
