/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BalanceResponseDto = {
  /**
   * Current balance as string for bigint safety
   */
  balance: string;
  /**
   * Last update timestamp (present for projected balance)
   */
  updatedAt?: string | undefined;
  /**
   * Point-in-time the balance was computed at (present for at-time queries)
   */
  asOf?: string | undefined;
};

/** @internal */
export const BalanceResponseDto$inboundSchema: z.ZodType<
  BalanceResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  balance: z.string(),
  updated_at: z.string().optional(),
  as_of: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "updated_at": "updatedAt",
    "as_of": "asOf",
  });
});
/** @internal */
export type BalanceResponseDto$Outbound = {
  balance: string;
  updated_at?: string | undefined;
  as_of?: string | undefined;
};

/** @internal */
export const BalanceResponseDto$outboundSchema: z.ZodType<
  BalanceResponseDto$Outbound,
  z.ZodTypeDef,
  BalanceResponseDto
> = z.object({
  balance: z.string(),
  updatedAt: z.string().optional(),
  asOf: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    updatedAt: "updated_at",
    asOf: "as_of",
  });
});

export function balanceResponseDtoToJSON(
  balanceResponseDto: BalanceResponseDto,
): string {
  return JSON.stringify(
    BalanceResponseDto$outboundSchema.parse(balanceResponseDto),
  );
}
export function balanceResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<BalanceResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BalanceResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BalanceResponseDto' from JSON`,
  );
}
