/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateAccountDto = {
  /**
   * Human-readable name for the account
   */
  name?: string | undefined;
  /**
   * The owner ID this account belongs to (e.g. customer ID)
   */
  customerId: string;
  /**
   * Label for the unit of currency/credits
   */
  unitLabel?: string | undefined;
  /**
   * Seed the account with this many credits on creation
   */
  initialBalance?: string | undefined;
};

/** @internal */
export const CreateAccountDto$inboundSchema: z.ZodType<
  CreateAccountDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().default("default"),
  customer_id: z.string(),
  unit_label: z.string().default("credits"),
  initial_balance: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "unit_label": "unitLabel",
    "initial_balance": "initialBalance",
  });
});
/** @internal */
export type CreateAccountDto$Outbound = {
  name: string;
  customer_id: string;
  unit_label: string;
  initial_balance?: string | undefined;
};

/** @internal */
export const CreateAccountDto$outboundSchema: z.ZodType<
  CreateAccountDto$Outbound,
  z.ZodTypeDef,
  CreateAccountDto
> = z.object({
  name: z.string().default("default"),
  customerId: z.string(),
  unitLabel: z.string().default("credits"),
  initialBalance: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    unitLabel: "unit_label",
    initialBalance: "initial_balance",
  });
});

export function createAccountDtoToJSON(
  createAccountDto: CreateAccountDto,
): string {
  return JSON.stringify(
    CreateAccountDto$outboundSchema.parse(createAccountDto),
  );
}
export function createAccountDtoFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccountDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAccountDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccountDto' from JSON`,
  );
}
