/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateCustomerRequestEntity = {
  /**
   * The email address of the customer.
   */
  email: string;
  /**
   * The full name of the customer.
   */
  name: string;
  /**
   * Additional metadata for the customer.
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const CreateCustomerRequestEntity$inboundSchema: z.ZodType<
  CreateCustomerRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  name: z.string(),
  metadata: z.record(z.any()).optional(),
});
/** @internal */
export type CreateCustomerRequestEntity$Outbound = {
  email: string;
  name: string;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const CreateCustomerRequestEntity$outboundSchema: z.ZodType<
  CreateCustomerRequestEntity$Outbound,
  z.ZodTypeDef,
  CreateCustomerRequestEntity
> = z.object({
  email: z.string(),
  name: z.string(),
  metadata: z.record(z.any()).optional(),
});

export function createCustomerRequestEntityToJSON(
  createCustomerRequestEntity: CreateCustomerRequestEntity,
): string {
  return JSON.stringify(
    CreateCustomerRequestEntity$outboundSchema.parse(
      createCustomerRequestEntity,
    ),
  );
}
export function createCustomerRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<CreateCustomerRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCustomerRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCustomerRequestEntity' from JSON`,
  );
}
