/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreditDebitRequestDto = {
  /**
   * Amount to credit or debit (string to support large numbers)
   */
  amount: string;
  /**
   * Your reference ID to link this transaction to an event in your system (e.g. order ID, campaign ID)
   */
  reference: string;
  /**
   * Idempotency key to prevent duplicate transactions
   */
  idempotencyKey: string;
};

/** @internal */
export const CreditDebitRequestDto$inboundSchema: z.ZodType<
  CreditDebitRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.string(),
  reference: z.string(),
  idempotency_key: z.string(),
}).transform((v) => {
  return remap$(v, {
    "idempotency_key": "idempotencyKey",
  });
});
/** @internal */
export type CreditDebitRequestDto$Outbound = {
  amount: string;
  reference: string;
  idempotency_key: string;
};

/** @internal */
export const CreditDebitRequestDto$outboundSchema: z.ZodType<
  CreditDebitRequestDto$Outbound,
  z.ZodTypeDef,
  CreditDebitRequestDto
> = z.object({
  amount: z.string(),
  reference: z.string(),
  idempotencyKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency_key",
  });
});

export function creditDebitRequestDtoToJSON(
  creditDebitRequestDto: CreditDebitRequestDto,
): string {
  return JSON.stringify(
    CreditDebitRequestDto$outboundSchema.parse(creditDebitRequestDto),
  );
}
export function creditDebitRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<CreditDebitRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditDebitRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditDebitRequestDto' from JSON`,
  );
}
