/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Error category
 */
export const CustomerCreditsErrorDetailDtoType = {
  InvalidRequestError: "invalid_request_error",
  ApiError: "api_error",
  AuthenticationError: "authentication_error",
  RateLimitError: "rate_limit_error",
} as const;
/**
 * Error category
 */
export type CustomerCreditsErrorDetailDtoType = ClosedEnum<
  typeof CustomerCreditsErrorDetailDtoType
>;

/**
 * Machine-readable error code
 */
export type Code = {};

/**
 * The parameter related to the error, if applicable
 */
export type Param = {};

export type CustomerCreditsErrorDetailDto = {
  /**
   * Error category
   */
  type: CustomerCreditsErrorDetailDtoType;
  /**
   * Machine-readable error code
   */
  code: Code | null;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * The parameter related to the error, if applicable
   */
  param?: Param | null | undefined;
  /**
   * Unique request identifier for support
   */
  requestId: string;
};

/** @internal */
export const CustomerCreditsErrorDetailDtoType$inboundSchema: z.ZodNativeEnum<
  typeof CustomerCreditsErrorDetailDtoType
> = z.nativeEnum(CustomerCreditsErrorDetailDtoType);
/** @internal */
export const CustomerCreditsErrorDetailDtoType$outboundSchema: z.ZodNativeEnum<
  typeof CustomerCreditsErrorDetailDtoType
> = CustomerCreditsErrorDetailDtoType$inboundSchema;

/** @internal */
export const Code$inboundSchema: z.ZodType<Code, z.ZodTypeDef, unknown> = z
  .object({});
/** @internal */
export type Code$Outbound = {};

/** @internal */
export const Code$outboundSchema: z.ZodType<Code$Outbound, z.ZodTypeDef, Code> =
  z.object({});

export function codeToJSON(code: Code): string {
  return JSON.stringify(Code$outboundSchema.parse(code));
}
export function codeFromJSON(
  jsonString: string,
): SafeParseResult<Code, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Code$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Code' from JSON`,
  );
}

/** @internal */
export const Param$inboundSchema: z.ZodType<Param, z.ZodTypeDef, unknown> = z
  .object({});
/** @internal */
export type Param$Outbound = {};

/** @internal */
export const Param$outboundSchema: z.ZodType<
  Param$Outbound,
  z.ZodTypeDef,
  Param
> = z.object({});

export function paramToJSON(param: Param): string {
  return JSON.stringify(Param$outboundSchema.parse(param));
}
export function paramFromJSON(
  jsonString: string,
): SafeParseResult<Param, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Param$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Param' from JSON`,
  );
}

/** @internal */
export const CustomerCreditsErrorDetailDto$inboundSchema: z.ZodType<
  CustomerCreditsErrorDetailDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CustomerCreditsErrorDetailDtoType$inboundSchema,
  code: z.nullable(z.lazy(() => Code$inboundSchema)),
  message: z.string(),
  param: z.nullable(z.lazy(() => Param$inboundSchema)).optional(),
  request_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});
/** @internal */
export type CustomerCreditsErrorDetailDto$Outbound = {
  type: string;
  code: Code$Outbound | null;
  message: string;
  param?: Param$Outbound | null | undefined;
  request_id: string;
};

/** @internal */
export const CustomerCreditsErrorDetailDto$outboundSchema: z.ZodType<
  CustomerCreditsErrorDetailDto$Outbound,
  z.ZodTypeDef,
  CustomerCreditsErrorDetailDto
> = z.object({
  type: CustomerCreditsErrorDetailDtoType$outboundSchema,
  code: z.nullable(z.lazy(() => Code$outboundSchema)),
  message: z.string(),
  param: z.nullable(z.lazy(() => Param$outboundSchema)).optional(),
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

export function customerCreditsErrorDetailDtoToJSON(
  customerCreditsErrorDetailDto: CustomerCreditsErrorDetailDto,
): string {
  return JSON.stringify(
    CustomerCreditsErrorDetailDto$outboundSchema.parse(
      customerCreditsErrorDetailDto,
    ),
  );
}
export function customerCreditsErrorDetailDtoFromJSON(
  jsonString: string,
): SafeParseResult<CustomerCreditsErrorDetailDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerCreditsErrorDetailDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerCreditsErrorDetailDto' from JSON`,
  );
}
