/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DiscountEntity,
  DiscountEntity$inboundSchema,
  DiscountEntity$Outbound,
  DiscountEntity$outboundSchema,
} from "./discountentity.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";

export type DiscountListEntity = {
  /**
   * List of discount items
   */
  items: Array<DiscountEntity>;
  /**
   * Pagination details for the list
   */
  pagination: PaginationEntity;
};

/** @internal */
export const DiscountListEntity$inboundSchema: z.ZodType<
  DiscountListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DiscountEntity$inboundSchema),
  pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export type DiscountListEntity$Outbound = {
  items: Array<DiscountEntity$Outbound>;
  pagination: PaginationEntity$Outbound;
};

/** @internal */
export const DiscountListEntity$outboundSchema: z.ZodType<
  DiscountListEntity$Outbound,
  z.ZodTypeDef,
  DiscountListEntity
> = z.object({
  items: z.array(DiscountEntity$outboundSchema),
  pagination: PaginationEntity$outboundSchema,
});

export function discountListEntityToJSON(
  discountListEntity: DiscountListEntity,
): string {
  return JSON.stringify(
    DiscountListEntity$outboundSchema.parse(discountListEntity),
  );
}
export function discountListEntityFromJSON(
  jsonString: string,
): SafeParseResult<DiscountListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiscountListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiscountListEntity' from JSON`,
  );
}
