/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CheckoutEntity,
  CheckoutEntity$inboundSchema,
  CheckoutEntity$Outbound,
  CheckoutEntity$outboundSchema,
} from "./checkoutentity.js";
import {
  CustomerEntity,
  CustomerEntity$inboundSchema,
  CustomerEntity$Outbound,
  CustomerEntity$outboundSchema,
} from "./customerentity.js";
import {
  EnvironmentMode,
  EnvironmentMode$inboundSchema,
  EnvironmentMode$outboundSchema,
} from "./environmentmode.js";
import {
  OrderEntity,
  OrderEntity$inboundSchema,
  OrderEntity$Outbound,
  OrderEntity$outboundSchema,
} from "./orderentity.js";
import {
  SubscriptionEntity,
  SubscriptionEntity$inboundSchema,
  SubscriptionEntity$Outbound,
  SubscriptionEntity$outboundSchema,
} from "./subscriptionentity.js";
import {
  TransactionEntity,
  TransactionEntity$inboundSchema,
  TransactionEntity$Outbound,
  TransactionEntity$outboundSchema,
} from "./transactionentity.js";

/**
 * The checkout associated with the dispute.
 */
export type DisputeEntityCheckout = CheckoutEntity | string;

/**
 * The order associated with the dispute.
 */
export type DisputeEntityOrder = OrderEntity | string;

/**
 * The subscription associated with the dispute.
 */
export type DisputeEntitySubscription = SubscriptionEntity | string;

/**
 * The customer associated with the dispute.
 */
export type DisputeEntityCustomer = CustomerEntity | string;

export type DisputeEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: EnvironmentMode;
  /**
   * String representing the object's type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * The disputed amount in cents. 1000 = $10.00
   */
  amount: number;
  /**
   * Three-letter ISO currency code, in uppercase. Must be a supported currency.
   */
  currency: string;
  /**
   * The transaction associated with the dispute.
   */
  transaction: TransactionEntity;
  /**
   * The checkout associated with the dispute.
   */
  checkout?: CheckoutEntity | string | undefined;
  /**
   * The order associated with the dispute.
   */
  order?: OrderEntity | string | undefined;
  /**
   * The subscription associated with the dispute.
   */
  subscription?: SubscriptionEntity | string | undefined;
  /**
   * The customer associated with the dispute.
   */
  customer?: CustomerEntity | string | undefined;
  /**
   * Creation date of the dispute as timestamp
   */
  createdAt: number;
};

/** @internal */
export const DisputeEntityCheckout$inboundSchema: z.ZodType<
  DisputeEntityCheckout,
  z.ZodTypeDef,
  unknown
> = z.union([CheckoutEntity$inboundSchema, z.string()]);
/** @internal */
export type DisputeEntityCheckout$Outbound = CheckoutEntity$Outbound | string;

/** @internal */
export const DisputeEntityCheckout$outboundSchema: z.ZodType<
  DisputeEntityCheckout$Outbound,
  z.ZodTypeDef,
  DisputeEntityCheckout
> = z.union([CheckoutEntity$outboundSchema, z.string()]);

export function disputeEntityCheckoutToJSON(
  disputeEntityCheckout: DisputeEntityCheckout,
): string {
  return JSON.stringify(
    DisputeEntityCheckout$outboundSchema.parse(disputeEntityCheckout),
  );
}
export function disputeEntityCheckoutFromJSON(
  jsonString: string,
): SafeParseResult<DisputeEntityCheckout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisputeEntityCheckout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisputeEntityCheckout' from JSON`,
  );
}

/** @internal */
export const DisputeEntityOrder$inboundSchema: z.ZodType<
  DisputeEntityOrder,
  z.ZodTypeDef,
  unknown
> = z.union([OrderEntity$inboundSchema, z.string()]);
/** @internal */
export type DisputeEntityOrder$Outbound = OrderEntity$Outbound | string;

/** @internal */
export const DisputeEntityOrder$outboundSchema: z.ZodType<
  DisputeEntityOrder$Outbound,
  z.ZodTypeDef,
  DisputeEntityOrder
> = z.union([OrderEntity$outboundSchema, z.string()]);

export function disputeEntityOrderToJSON(
  disputeEntityOrder: DisputeEntityOrder,
): string {
  return JSON.stringify(
    DisputeEntityOrder$outboundSchema.parse(disputeEntityOrder),
  );
}
export function disputeEntityOrderFromJSON(
  jsonString: string,
): SafeParseResult<DisputeEntityOrder, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisputeEntityOrder$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisputeEntityOrder' from JSON`,
  );
}

/** @internal */
export const DisputeEntitySubscription$inboundSchema: z.ZodType<
  DisputeEntitySubscription,
  z.ZodTypeDef,
  unknown
> = z.union([SubscriptionEntity$inboundSchema, z.string()]);
/** @internal */
export type DisputeEntitySubscription$Outbound =
  | SubscriptionEntity$Outbound
  | string;

/** @internal */
export const DisputeEntitySubscription$outboundSchema: z.ZodType<
  DisputeEntitySubscription$Outbound,
  z.ZodTypeDef,
  DisputeEntitySubscription
> = z.union([SubscriptionEntity$outboundSchema, z.string()]);

export function disputeEntitySubscriptionToJSON(
  disputeEntitySubscription: DisputeEntitySubscription,
): string {
  return JSON.stringify(
    DisputeEntitySubscription$outboundSchema.parse(disputeEntitySubscription),
  );
}
export function disputeEntitySubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<DisputeEntitySubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisputeEntitySubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisputeEntitySubscription' from JSON`,
  );
}

/** @internal */
export const DisputeEntityCustomer$inboundSchema: z.ZodType<
  DisputeEntityCustomer,
  z.ZodTypeDef,
  unknown
> = z.union([CustomerEntity$inboundSchema, z.string()]);
/** @internal */
export type DisputeEntityCustomer$Outbound = CustomerEntity$Outbound | string;

/** @internal */
export const DisputeEntityCustomer$outboundSchema: z.ZodType<
  DisputeEntityCustomer$Outbound,
  z.ZodTypeDef,
  DisputeEntityCustomer
> = z.union([CustomerEntity$outboundSchema, z.string()]);

export function disputeEntityCustomerToJSON(
  disputeEntityCustomer: DisputeEntityCustomer,
): string {
  return JSON.stringify(
    DisputeEntityCustomer$outboundSchema.parse(disputeEntityCustomer),
  );
}
export function disputeEntityCustomerFromJSON(
  jsonString: string,
): SafeParseResult<DisputeEntityCustomer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisputeEntityCustomer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisputeEntityCustomer' from JSON`,
  );
}

/** @internal */
export const DisputeEntity$inboundSchema: z.ZodType<
  DisputeEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$inboundSchema,
  object: z.string(),
  amount: z.number(),
  currency: z.string(),
  transaction: TransactionEntity$inboundSchema,
  checkout: z.union([CheckoutEntity$inboundSchema, z.string()]).optional(),
  order: z.union([OrderEntity$inboundSchema, z.string()]).optional(),
  subscription: z.union([SubscriptionEntity$inboundSchema, z.string()])
    .optional(),
  customer: z.union([CustomerEntity$inboundSchema, z.string()]).optional(),
  created_at: z.number(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type DisputeEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  amount: number;
  currency: string;
  transaction: TransactionEntity$Outbound;
  checkout?: CheckoutEntity$Outbound | string | undefined;
  order?: OrderEntity$Outbound | string | undefined;
  subscription?: SubscriptionEntity$Outbound | string | undefined;
  customer?: CustomerEntity$Outbound | string | undefined;
  created_at: number;
};

/** @internal */
export const DisputeEntity$outboundSchema: z.ZodType<
  DisputeEntity$Outbound,
  z.ZodTypeDef,
  DisputeEntity
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$outboundSchema,
  object: z.string(),
  amount: z.number(),
  currency: z.string(),
  transaction: TransactionEntity$outboundSchema,
  checkout: z.union([CheckoutEntity$outboundSchema, z.string()]).optional(),
  order: z.union([OrderEntity$outboundSchema, z.string()]).optional(),
  subscription: z.union([SubscriptionEntity$outboundSchema, z.string()])
    .optional(),
  customer: z.union([CustomerEntity$outboundSchema, z.string()]).optional(),
  createdAt: z.number(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function disputeEntityToJSON(disputeEntity: DisputeEntity): string {
  return JSON.stringify(DisputeEntity$outboundSchema.parse(disputeEntity));
}
export function disputeEntityFromJSON(
  jsonString: string,
): SafeParseResult<DisputeEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisputeEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisputeEntity' from JSON`,
  );
}
