/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Debit or credit side
 */
export const Side = {
  Debit: "debit",
  Credit: "credit",
} as const;
/**
 * Debit or credit side
 */
export type Side = ClosedEnum<typeof Side>;

export type EntryResponseDto = {
  /**
   * Entry ID
   */
  id: string;
  /**
   * Transaction ID
   */
  transactionId: string;
  /**
   * Account ID
   */
  accountId: string;
  /**
   * Debit or credit side
   */
  side: Side;
  /**
   * Amount as string for bigint safety
   */
  amount: string;
  /**
   * Creation timestamp
   */
  createdAt: string;
};

/** @internal */
export const Side$inboundSchema: z.ZodNativeEnum<typeof Side> = z.nativeEnum(
  Side,
);
/** @internal */
export const Side$outboundSchema: z.ZodNativeEnum<typeof Side> =
  Side$inboundSchema;

/** @internal */
export const EntryResponseDto$inboundSchema: z.ZodType<
  EntryResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  transaction_id: z.string(),
  account_id: z.string(),
  side: Side$inboundSchema,
  amount: z.string(),
  created_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "transaction_id": "transactionId",
    "account_id": "accountId",
    "created_at": "createdAt",
  });
});
/** @internal */
export type EntryResponseDto$Outbound = {
  id: string;
  transaction_id: string;
  account_id: string;
  side: string;
  amount: string;
  created_at: string;
};

/** @internal */
export const EntryResponseDto$outboundSchema: z.ZodType<
  EntryResponseDto$Outbound,
  z.ZodTypeDef,
  EntryResponseDto
> = z.object({
  id: z.string(),
  transactionId: z.string(),
  accountId: z.string(),
  side: Side$outboundSchema,
  amount: z.string(),
  createdAt: z.string(),
}).transform((v) => {
  return remap$(v, {
    transactionId: "transaction_id",
    accountId: "account_id",
    createdAt: "created_at",
  });
});

export function entryResponseDtoToJSON(
  entryResponseDto: EntryResponseDto,
): string {
  return JSON.stringify(
    EntryResponseDto$outboundSchema.parse(entryResponseDto),
  );
}
export function entryResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<EntryResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EntryResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntryResponseDto' from JSON`,
  );
}
