/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EntryResponseDto,
  EntryResponseDto$inboundSchema,
  EntryResponseDto$Outbound,
  EntryResponseDto$outboundSchema,
} from "./entryresponsedto.js";

export type EntryListResponseDto = {
  /**
   * Object type
   */
  object: string;
  /**
   * Array of entries
   */
  data: Array<EntryResponseDto>;
  /**
   * Whether more items exist beyond this page
   */
  hasMore: boolean;
};

/** @internal */
export const EntryListResponseDto$inboundSchema: z.ZodType<
  EntryListResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string(),
  data: z.array(EntryResponseDto$inboundSchema),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});
/** @internal */
export type EntryListResponseDto$Outbound = {
  object: string;
  data: Array<EntryResponseDto$Outbound>;
  has_more: boolean;
};

/** @internal */
export const EntryListResponseDto$outboundSchema: z.ZodType<
  EntryListResponseDto$Outbound,
  z.ZodTypeDef,
  EntryListResponseDto
> = z.object({
  object: z.string(),
  data: z.array(EntryResponseDto$outboundSchema),
  hasMore: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
  });
});

export function entryListResponseDtoToJSON(
  entryListResponseDto: EntryListResponseDto,
): string {
  return JSON.stringify(
    EntryListResponseDto$outboundSchema.parse(entryListResponseDto),
  );
}
export function entryListResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<EntryListResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EntryListResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntryListResponseDto' from JSON`,
  );
}
