/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LicenseEntity,
  LicenseEntity$inboundSchema,
  LicenseEntity$Outbound,
  LicenseEntity$outboundSchema,
} from "./licenseentity.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";

export type LicenseListEntity = {
  /**
   * List of license items
   */
  items: Array<LicenseEntity>;
  /**
   * Pagination details for the list
   */
  pagination: PaginationEntity;
};

/** @internal */
export const LicenseListEntity$inboundSchema: z.ZodType<
  LicenseListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(LicenseEntity$inboundSchema),
  pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export type LicenseListEntity$Outbound = {
  items: Array<LicenseEntity$Outbound>;
  pagination: PaginationEntity$Outbound;
};

/** @internal */
export const LicenseListEntity$outboundSchema: z.ZodType<
  LicenseListEntity$Outbound,
  z.ZodTypeDef,
  LicenseListEntity
> = z.object({
  items: z.array(LicenseEntity$outboundSchema),
  pagination: PaginationEntity$outboundSchema,
});

export function licenseListEntityToJSON(
  licenseListEntity: LicenseListEntity,
): string {
  return JSON.stringify(
    LicenseListEntity$outboundSchema.parse(licenseListEntity),
  );
}
export function licenseListEntityFromJSON(
  jsonString: string,
): SafeParseResult<LicenseListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LicenseListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LicenseListEntity' from JSON`,
  );
}
