/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrderEntity,
  OrderEntity$inboundSchema,
  OrderEntity$Outbound,
  OrderEntity$outboundSchema,
} from "./orderentity.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";

export type OrderListEntity = {
  /**
   * List of order items
   */
  items: Array<OrderEntity>;
  /**
   * Pagination details for the list
   */
  pagination: PaginationEntity;
};

/** @internal */
export const OrderListEntity$inboundSchema: z.ZodType<
  OrderListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(OrderEntity$inboundSchema),
  pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export type OrderListEntity$Outbound = {
  items: Array<OrderEntity$Outbound>;
  pagination: PaginationEntity$Outbound;
};

/** @internal */
export const OrderListEntity$outboundSchema: z.ZodType<
  OrderListEntity$Outbound,
  z.ZodTypeDef,
  OrderListEntity
> = z.object({
  items: z.array(OrderEntity$outboundSchema),
  pagination: PaginationEntity$outboundSchema,
});

export function orderListEntityToJSON(
  orderListEntity: OrderListEntity,
): string {
  return JSON.stringify(OrderListEntity$outboundSchema.parse(orderListEntity));
}
export function orderListEntityFromJSON(
  jsonString: string,
): SafeParseResult<OrderListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderListEntity' from JSON`,
  );
}
