/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Reason for the refund.
 */
export const RefundReason = {
  Duplicate: "duplicate",
  Fraudulent: "fraudulent",
  RequestedByCustomer: "requested_by_customer",
  Other: "other",
} as const;
/**
 * Reason for the refund.
 */
export type RefundReason = ClosedEnum<typeof RefundReason>;

/** @internal */
export const RefundReason$inboundSchema: z.ZodNativeEnum<typeof RefundReason> =
  z.nativeEnum(RefundReason);
/** @internal */
export const RefundReason$outboundSchema: z.ZodNativeEnum<typeof RefundReason> =
  RefundReason$inboundSchema;
