/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CheckoutEntity,
  CheckoutEntity$inboundSchema,
  CheckoutEntity$Outbound,
  CheckoutEntity$outboundSchema,
} from "./checkoutentity.js";
import {
  CustomerEntity,
  CustomerEntity$inboundSchema,
  CustomerEntity$Outbound,
  CustomerEntity$outboundSchema,
} from "./customerentity.js";
import {
  EnvironmentMode,
  EnvironmentMode$inboundSchema,
  EnvironmentMode$outboundSchema,
} from "./environmentmode.js";
import {
  OrderEntity,
  OrderEntity$inboundSchema,
  OrderEntity$Outbound,
  OrderEntity$outboundSchema,
} from "./orderentity.js";
import {
  RefundReason,
  RefundReason$inboundSchema,
  RefundReason$outboundSchema,
} from "./refundreason.js";
import {
  RefundStatus,
  RefundStatus$inboundSchema,
  RefundStatus$outboundSchema,
} from "./refundstatus.js";
import {
  SubscriptionEntity,
  SubscriptionEntity$inboundSchema,
  SubscriptionEntity$Outbound,
  SubscriptionEntity$outboundSchema,
} from "./subscriptionentity.js";
import {
  TransactionEntity,
  TransactionEntity$inboundSchema,
  TransactionEntity$Outbound,
  TransactionEntity$outboundSchema,
} from "./transactionentity.js";

/**
 * The checkout associated with the refund.
 */
export type Checkout = CheckoutEntity | string;

/**
 * The order associated with the refund.
 */
export type Order = OrderEntity | string;

/**
 * The subscription associated with the refund.
 */
export type RefundEntitySubscription = SubscriptionEntity | string;

/**
 * The customer associated with the refund.
 */
export type RefundEntityCustomer = CustomerEntity | string;

export type RefundEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: EnvironmentMode;
  /**
   * String representing the object’s type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * Status of the refund.
   */
  status: RefundStatus;
  /**
   * The refunded amount in cents. 1000 = $10.00
   */
  refundAmount: number;
  /**
   * Three-letter ISO currency code, in uppercase. Must be a supported currency.
   */
  refundCurrency: string;
  /**
   * Reason for the refund.
   */
  reason: RefundReason;
  /**
   * The transaction associated with the refund.
   */
  transaction: TransactionEntity;
  /**
   * The checkout associated with the refund.
   */
  checkout?: CheckoutEntity | string | undefined;
  /**
   * The order associated with the refund.
   */
  order?: OrderEntity | string | undefined;
  /**
   * The subscription associated with the refund.
   */
  subscription?: SubscriptionEntity | string | undefined;
  /**
   * The customer associated with the refund.
   */
  customer?: CustomerEntity | string | undefined;
  /**
   * Creation date of the order as timestamp
   */
  createdAt: number;
};

/** @internal */
export const Checkout$inboundSchema: z.ZodType<
  Checkout,
  z.ZodTypeDef,
  unknown
> = z.union([CheckoutEntity$inboundSchema, z.string()]);
/** @internal */
export type Checkout$Outbound = CheckoutEntity$Outbound | string;

/** @internal */
export const Checkout$outboundSchema: z.ZodType<
  Checkout$Outbound,
  z.ZodTypeDef,
  Checkout
> = z.union([CheckoutEntity$outboundSchema, z.string()]);

export function checkoutToJSON(checkout: Checkout): string {
  return JSON.stringify(Checkout$outboundSchema.parse(checkout));
}
export function checkoutFromJSON(
  jsonString: string,
): SafeParseResult<Checkout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Checkout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Checkout' from JSON`,
  );
}

/** @internal */
export const Order$inboundSchema: z.ZodType<Order, z.ZodTypeDef, unknown> = z
  .union([OrderEntity$inboundSchema, z.string()]);
/** @internal */
export type Order$Outbound = OrderEntity$Outbound | string;

/** @internal */
export const Order$outboundSchema: z.ZodType<
  Order$Outbound,
  z.ZodTypeDef,
  Order
> = z.union([OrderEntity$outboundSchema, z.string()]);

export function orderToJSON(order: Order): string {
  return JSON.stringify(Order$outboundSchema.parse(order));
}
export function orderFromJSON(
  jsonString: string,
): SafeParseResult<Order, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Order$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Order' from JSON`,
  );
}

/** @internal */
export const RefundEntitySubscription$inboundSchema: z.ZodType<
  RefundEntitySubscription,
  z.ZodTypeDef,
  unknown
> = z.union([SubscriptionEntity$inboundSchema, z.string()]);
/** @internal */
export type RefundEntitySubscription$Outbound =
  | SubscriptionEntity$Outbound
  | string;

/** @internal */
export const RefundEntitySubscription$outboundSchema: z.ZodType<
  RefundEntitySubscription$Outbound,
  z.ZodTypeDef,
  RefundEntitySubscription
> = z.union([SubscriptionEntity$outboundSchema, z.string()]);

export function refundEntitySubscriptionToJSON(
  refundEntitySubscription: RefundEntitySubscription,
): string {
  return JSON.stringify(
    RefundEntitySubscription$outboundSchema.parse(refundEntitySubscription),
  );
}
export function refundEntitySubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<RefundEntitySubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefundEntitySubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefundEntitySubscription' from JSON`,
  );
}

/** @internal */
export const RefundEntityCustomer$inboundSchema: z.ZodType<
  RefundEntityCustomer,
  z.ZodTypeDef,
  unknown
> = z.union([CustomerEntity$inboundSchema, z.string()]);
/** @internal */
export type RefundEntityCustomer$Outbound = CustomerEntity$Outbound | string;

/** @internal */
export const RefundEntityCustomer$outboundSchema: z.ZodType<
  RefundEntityCustomer$Outbound,
  z.ZodTypeDef,
  RefundEntityCustomer
> = z.union([CustomerEntity$outboundSchema, z.string()]);

export function refundEntityCustomerToJSON(
  refundEntityCustomer: RefundEntityCustomer,
): string {
  return JSON.stringify(
    RefundEntityCustomer$outboundSchema.parse(refundEntityCustomer),
  );
}
export function refundEntityCustomerFromJSON(
  jsonString: string,
): SafeParseResult<RefundEntityCustomer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefundEntityCustomer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefundEntityCustomer' from JSON`,
  );
}

/** @internal */
export const RefundEntity$inboundSchema: z.ZodType<
  RefundEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$inboundSchema,
  object: z.string(),
  status: RefundStatus$inboundSchema,
  refund_amount: z.number(),
  refund_currency: z.string(),
  reason: RefundReason$inboundSchema,
  transaction: TransactionEntity$inboundSchema,
  checkout: z.union([CheckoutEntity$inboundSchema, z.string()]).optional(),
  order: z.union([OrderEntity$inboundSchema, z.string()]).optional(),
  subscription: z.union([SubscriptionEntity$inboundSchema, z.string()])
    .optional(),
  customer: z.union([CustomerEntity$inboundSchema, z.string()]).optional(),
  created_at: z.number(),
}).transform((v) => {
  return remap$(v, {
    "refund_amount": "refundAmount",
    "refund_currency": "refundCurrency",
    "created_at": "createdAt",
  });
});
/** @internal */
export type RefundEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  status: string;
  refund_amount: number;
  refund_currency: string;
  reason: string;
  transaction: TransactionEntity$Outbound;
  checkout?: CheckoutEntity$Outbound | string | undefined;
  order?: OrderEntity$Outbound | string | undefined;
  subscription?: SubscriptionEntity$Outbound | string | undefined;
  customer?: CustomerEntity$Outbound | string | undefined;
  created_at: number;
};

/** @internal */
export const RefundEntity$outboundSchema: z.ZodType<
  RefundEntity$Outbound,
  z.ZodTypeDef,
  RefundEntity
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$outboundSchema,
  object: z.string(),
  status: RefundStatus$outboundSchema,
  refundAmount: z.number(),
  refundCurrency: z.string(),
  reason: RefundReason$outboundSchema,
  transaction: TransactionEntity$outboundSchema,
  checkout: z.union([CheckoutEntity$outboundSchema, z.string()]).optional(),
  order: z.union([OrderEntity$outboundSchema, z.string()]).optional(),
  subscription: z.union([SubscriptionEntity$outboundSchema, z.string()])
    .optional(),
  customer: z.union([CustomerEntity$outboundSchema, z.string()]).optional(),
  createdAt: z.number(),
}).transform((v) => {
  return remap$(v, {
    refundAmount: "refund_amount",
    refundCurrency: "refund_currency",
    createdAt: "created_at",
  });
});

export function refundEntityToJSON(refundEntity: RefundEntity): string {
  return JSON.stringify(RefundEntity$outboundSchema.parse(refundEntity));
}
export function refundEntityFromJSON(
  jsonString: string,
): SafeParseResult<RefundEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefundEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefundEntity' from JSON`,
  );
}
