/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ScreenPromptRequest = {
  /**
   * The text prompt to evaluate against content policies.
   */
  prompt: string;
  /**
   * An optional identifier to associate this request with.
   */
  externalId?: string | undefined;
};

/** @internal */
export const ScreenPromptRequest$inboundSchema: z.ZodType<
  ScreenPromptRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  prompt: z.string(),
  external_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "external_id": "externalId",
  });
});
/** @internal */
export type ScreenPromptRequest$Outbound = {
  prompt: string;
  external_id?: string | undefined;
};

/** @internal */
export const ScreenPromptRequest$outboundSchema: z.ZodType<
  ScreenPromptRequest$Outbound,
  z.ZodTypeDef,
  ScreenPromptRequest
> = z.object({
  prompt: z.string(),
  externalId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    externalId: "external_id",
  });
});

export function screenPromptRequestToJSON(
  screenPromptRequest: ScreenPromptRequest,
): string {
  return JSON.stringify(
    ScreenPromptRequest$outboundSchema.parse(screenPromptRequest),
  );
}
export function screenPromptRequestFromJSON(
  jsonString: string,
): SafeParseResult<ScreenPromptRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScreenPromptRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScreenPromptRequest' from JSON`,
  );
}
