/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ProductCurrency,
  ProductCurrency$inboundSchema,
  ProductCurrency$outboundSchema,
} from "./productcurrency.js";
import {
  ProductRequestBillingPeriod,
  ProductRequestBillingPeriod$inboundSchema,
  ProductRequestBillingPeriod$outboundSchema,
} from "./productrequestbillingperiod.js";
import {
  ProductRequestBillingType,
  ProductRequestBillingType$inboundSchema,
  ProductRequestBillingType$outboundSchema,
} from "./productrequestbillingtype.js";
import {
  TaxMode,
  TaxMode$inboundSchema,
  TaxMode$outboundSchema,
} from "./taxmode.js";

/**
 * Product update payload. Only supplied fields change. Changing a price field mints a new default price; existing subscriptions keep the price they were purchased under.
 */
export type UpdateProductRequestEntity = {
  /**
   * Name of the product
   */
  name?: string | undefined;
  /**
   * Description of the product
   */
  description?: string | undefined;
  /**
   * URL of the product image
   */
  imageUrl?: string | undefined;
  /**
   * The URL to which the user will be redirected after successfull payment.
   */
  defaultSuccessUrl?: string | undefined;
  /**
   * The price of the product in cents. Must be 0 (free product) or at least 100 (one whole unit of the currency).
   */
  price?: number | undefined;
  /**
   * Three-letter ISO currency code, in uppercase. Must be a supported currency.
   */
  currency?: ProductCurrency | undefined;
  /**
   * Indicates the billing method for the customer. It can either be a `recurring` billing cycle or a `onetime` payment.
   */
  billingType?: ProductRequestBillingType | undefined;
  /**
   * Billing period, required if billing_type is recurring
   */
  billingPeriod?: ProductRequestBillingPeriod | undefined;
  /**
   * Specifies the tax calculation mode for the transaction. If set to "inclusive," the tax is included in the price. If set to "exclusive," the tax is added on top of the price.
   */
  taxMode?: TaxMode | undefined;
  /**
   * Enable pay-what-you-want pricing: the customer chooses the amount at checkout. The `price` field acts as the minimum the customer must pay. Only supported for one-time payment products.
   */
  payWhatYouWant?: boolean | undefined;
  /**
   * Suggested amount in cents, pre-filled at checkout when pay_what_you_want is enabled. Must be greater than or equal to `price` (the minimum). Ignored when pay_what_you_want is disabled.
   */
  suggestedPrice?: number | undefined;
};

/** @internal */
export const UpdateProductRequestEntity$inboundSchema: z.ZodType<
  UpdateProductRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  image_url: z.string().optional(),
  default_success_url: z.string().optional(),
  price: z.number().int().optional(),
  currency: ProductCurrency$inboundSchema.optional(),
  billing_type: ProductRequestBillingType$inboundSchema.optional(),
  billing_period: ProductRequestBillingPeriod$inboundSchema.optional(),
  tax_mode: TaxMode$inboundSchema.optional(),
  pay_what_you_want: z.boolean().optional(),
  suggested_price: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "image_url": "imageUrl",
    "default_success_url": "defaultSuccessUrl",
    "billing_type": "billingType",
    "billing_period": "billingPeriod",
    "tax_mode": "taxMode",
    "pay_what_you_want": "payWhatYouWant",
    "suggested_price": "suggestedPrice",
  });
});
/** @internal */
export type UpdateProductRequestEntity$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  image_url?: string | undefined;
  default_success_url?: string | undefined;
  price?: number | undefined;
  currency?: string | undefined;
  billing_type?: string | undefined;
  billing_period?: string | undefined;
  tax_mode?: string | undefined;
  pay_what_you_want?: boolean | undefined;
  suggested_price?: number | undefined;
};

/** @internal */
export const UpdateProductRequestEntity$outboundSchema: z.ZodType<
  UpdateProductRequestEntity$Outbound,
  z.ZodTypeDef,
  UpdateProductRequestEntity
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  imageUrl: z.string().optional(),
  defaultSuccessUrl: z.string().optional(),
  price: z.number().int().optional(),
  currency: ProductCurrency$outboundSchema.optional(),
  billingType: ProductRequestBillingType$outboundSchema.optional(),
  billingPeriod: ProductRequestBillingPeriod$outboundSchema.optional(),
  taxMode: TaxMode$outboundSchema.optional(),
  payWhatYouWant: z.boolean().optional(),
  suggestedPrice: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
    defaultSuccessUrl: "default_success_url",
    billingType: "billing_type",
    billingPeriod: "billing_period",
    taxMode: "tax_mode",
    payWhatYouWant: "pay_what_you_want",
    suggestedPrice: "suggested_price",
  });
});

export function updateProductRequestEntityToJSON(
  updateProductRequestEntity: UpdateProductRequestEntity,
): string {
  return JSON.stringify(
    UpdateProductRequestEntity$outboundSchema.parse(updateProductRequestEntity),
  );
}
export function updateProductRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProductRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProductRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProductRequestEntity' from JSON`,
  );
}
