/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UsageEntity = {
  /**
   * Number of units consumed by this call.
   */
  units: number;
};

/** @internal */
export const UsageEntity$inboundSchema: z.ZodType<
  UsageEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  units: z.number(),
});
/** @internal */
export type UsageEntity$Outbound = {
  units: number;
};

/** @internal */
export const UsageEntity$outboundSchema: z.ZodType<
  UsageEntity$Outbound,
  z.ZodTypeDef,
  UsageEntity
> = z.object({
  units: z.number(),
});

export function usageEntityToJSON(usageEntity: UsageEntity): string {
  return JSON.stringify(UsageEntity$outboundSchema.parse(usageEntity));
}
export function usageEntityFromJSON(
  jsonString: string,
): SafeParseResult<UsageEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageEntity' from JSON`,
  );
}
