/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookCheckoutCompletedEventEntity,
  WebhookCheckoutCompletedEventEntity$inboundSchema,
  WebhookCheckoutCompletedEventEntity$Outbound,
  WebhookCheckoutCompletedEventEntity$outboundSchema,
} from "./webhookcheckoutcompletedevententity.js";
import {
  WebhookDisputeCreatedEventEntity,
  WebhookDisputeCreatedEventEntity$inboundSchema,
  WebhookDisputeCreatedEventEntity$Outbound,
  WebhookDisputeCreatedEventEntity$outboundSchema,
} from "./webhookdisputecreatedevententity.js";
import {
  WebhookRefundCreatedEventEntity,
  WebhookRefundCreatedEventEntity$inboundSchema,
  WebhookRefundCreatedEventEntity$Outbound,
  WebhookRefundCreatedEventEntity$outboundSchema,
} from "./webhookrefundcreatedevententity.js";
import {
  WebhookSubscriptionActiveEventEntity,
  WebhookSubscriptionActiveEventEntity$inboundSchema,
  WebhookSubscriptionActiveEventEntity$Outbound,
  WebhookSubscriptionActiveEventEntity$outboundSchema,
} from "./webhooksubscriptionactiveevententity.js";
import {
  WebhookSubscriptionCanceledEventEntity,
  WebhookSubscriptionCanceledEventEntity$inboundSchema,
  WebhookSubscriptionCanceledEventEntity$Outbound,
  WebhookSubscriptionCanceledEventEntity$outboundSchema,
} from "./webhooksubscriptioncanceledevententity.js";
import {
  WebhookSubscriptionExpiredEventEntity,
  WebhookSubscriptionExpiredEventEntity$inboundSchema,
  WebhookSubscriptionExpiredEventEntity$Outbound,
  WebhookSubscriptionExpiredEventEntity$outboundSchema,
} from "./webhooksubscriptionexpiredevententity.js";
import {
  WebhookSubscriptionPaidEventEntity,
  WebhookSubscriptionPaidEventEntity$inboundSchema,
  WebhookSubscriptionPaidEventEntity$Outbound,
  WebhookSubscriptionPaidEventEntity$outboundSchema,
} from "./webhooksubscriptionpaidevententity.js";
import {
  WebhookSubscriptionPastDueEventEntity,
  WebhookSubscriptionPastDueEventEntity$inboundSchema,
  WebhookSubscriptionPastDueEventEntity$Outbound,
  WebhookSubscriptionPastDueEventEntity$outboundSchema,
} from "./webhooksubscriptionpastdueevententity.js";
import {
  WebhookSubscriptionPausedEventEntity,
  WebhookSubscriptionPausedEventEntity$inboundSchema,
  WebhookSubscriptionPausedEventEntity$Outbound,
  WebhookSubscriptionPausedEventEntity$outboundSchema,
} from "./webhooksubscriptionpausedevententity.js";
import {
  WebhookSubscriptionScheduledCancelEventEntity,
  WebhookSubscriptionScheduledCancelEventEntity$inboundSchema,
  WebhookSubscriptionScheduledCancelEventEntity$Outbound,
  WebhookSubscriptionScheduledCancelEventEntity$outboundSchema,
} from "./webhooksubscriptionscheduledcancelevententity.js";
import {
  WebhookSubscriptionTrialingEventEntity,
  WebhookSubscriptionTrialingEventEntity$inboundSchema,
  WebhookSubscriptionTrialingEventEntity$Outbound,
  WebhookSubscriptionTrialingEventEntity$outboundSchema,
} from "./webhooksubscriptiontrialingevententity.js";
import {
  WebhookSubscriptionUnpaidEventEntity,
  WebhookSubscriptionUnpaidEventEntity$inboundSchema,
  WebhookSubscriptionUnpaidEventEntity$Outbound,
  WebhookSubscriptionUnpaidEventEntity$outboundSchema,
} from "./webhooksubscriptionunpaidevententity.js";
import {
  WebhookSubscriptionUpdateEventEntity,
  WebhookSubscriptionUpdateEventEntity$inboundSchema,
  WebhookSubscriptionUpdateEventEntity$Outbound,
  WebhookSubscriptionUpdateEventEntity$outboundSchema,
} from "./webhooksubscriptionupdateevententity.js";

/**
 * Webhook event delivered by Creem. The eventType property determines the shape of object.
 */
export type WebhookEventEntity =
  | (WebhookCheckoutCompletedEventEntity & { eventType: "checkout.completed" })
  | (WebhookRefundCreatedEventEntity & { eventType: "refund.created" })
  | (WebhookDisputeCreatedEventEntity & { eventType: "dispute.created" })
  | (WebhookSubscriptionActiveEventEntity & {
    eventType: "subscription.active";
  })
  | (WebhookSubscriptionTrialingEventEntity & {
    eventType: "subscription.trialing";
  })
  | (WebhookSubscriptionCanceledEventEntity & {
    eventType: "subscription.canceled";
  })
  | (WebhookSubscriptionScheduledCancelEventEntity & {
    eventType: "subscription.scheduled_cancel";
  })
  | (WebhookSubscriptionPaidEventEntity & { eventType: "subscription.paid" })
  | (WebhookSubscriptionExpiredEventEntity & {
    eventType: "subscription.expired";
  })
  | (WebhookSubscriptionUnpaidEventEntity & {
    eventType: "subscription.unpaid";
  })
  | (WebhookSubscriptionUpdateEventEntity & {
    eventType: "subscription.update";
  })
  | (WebhookSubscriptionPastDueEventEntity & {
    eventType: "subscription.past_due";
  })
  | (WebhookSubscriptionPausedEventEntity & {
    eventType: "subscription.paused";
  });

/** @internal */
export const WebhookEventEntity$inboundSchema: z.ZodType<
  WebhookEventEntity,
  z.ZodTypeDef,
  unknown
> = z.union([
  WebhookCheckoutCompletedEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("checkout.completed") }),
  ),
  WebhookRefundCreatedEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("refund.created") }),
  ),
  WebhookDisputeCreatedEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("dispute.created") }),
  ),
  WebhookSubscriptionActiveEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.active") }),
  ),
  WebhookSubscriptionTrialingEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.trialing") }),
  ),
  WebhookSubscriptionCanceledEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.canceled") }),
  ),
  WebhookSubscriptionScheduledCancelEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.scheduled_cancel") }),
  ),
  WebhookSubscriptionPaidEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.paid") }),
  ),
  WebhookSubscriptionExpiredEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.expired") }),
  ),
  WebhookSubscriptionUnpaidEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.unpaid") }),
  ),
  WebhookSubscriptionUpdateEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.update") }),
  ),
  WebhookSubscriptionPastDueEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.past_due") }),
  ),
  WebhookSubscriptionPausedEventEntity$inboundSchema.and(
    z.object({ eventType: z.literal("subscription.paused") }),
  ),
]);
/** @internal */
export type WebhookEventEntity$Outbound =
  | (WebhookCheckoutCompletedEventEntity$Outbound & {
    eventType: "checkout.completed";
  })
  | (WebhookRefundCreatedEventEntity$Outbound & { eventType: "refund.created" })
  | (WebhookDisputeCreatedEventEntity$Outbound & {
    eventType: "dispute.created";
  })
  | (WebhookSubscriptionActiveEventEntity$Outbound & {
    eventType: "subscription.active";
  })
  | (WebhookSubscriptionTrialingEventEntity$Outbound & {
    eventType: "subscription.trialing";
  })
  | (WebhookSubscriptionCanceledEventEntity$Outbound & {
    eventType: "subscription.canceled";
  })
  | (WebhookSubscriptionScheduledCancelEventEntity$Outbound & {
    eventType: "subscription.scheduled_cancel";
  })
  | (WebhookSubscriptionPaidEventEntity$Outbound & {
    eventType: "subscription.paid";
  })
  | (WebhookSubscriptionExpiredEventEntity$Outbound & {
    eventType: "subscription.expired";
  })
  | (WebhookSubscriptionUnpaidEventEntity$Outbound & {
    eventType: "subscription.unpaid";
  })
  | (WebhookSubscriptionUpdateEventEntity$Outbound & {
    eventType: "subscription.update";
  })
  | (WebhookSubscriptionPastDueEventEntity$Outbound & {
    eventType: "subscription.past_due";
  })
  | (WebhookSubscriptionPausedEventEntity$Outbound & {
    eventType: "subscription.paused";
  });

/** @internal */
export const WebhookEventEntity$outboundSchema: z.ZodType<
  WebhookEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookEventEntity
> = z.union([
  WebhookCheckoutCompletedEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("checkout.completed") }),
  ),
  WebhookRefundCreatedEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("refund.created") }),
  ),
  WebhookDisputeCreatedEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("dispute.created") }),
  ),
  WebhookSubscriptionActiveEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.active") }),
  ),
  WebhookSubscriptionTrialingEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.trialing") }),
  ),
  WebhookSubscriptionCanceledEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.canceled") }),
  ),
  WebhookSubscriptionScheduledCancelEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.scheduled_cancel") }),
  ),
  WebhookSubscriptionPaidEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.paid") }),
  ),
  WebhookSubscriptionExpiredEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.expired") }),
  ),
  WebhookSubscriptionUnpaidEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.unpaid") }),
  ),
  WebhookSubscriptionUpdateEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.update") }),
  ),
  WebhookSubscriptionPastDueEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.past_due") }),
  ),
  WebhookSubscriptionPausedEventEntity$outboundSchema.and(
    z.object({ eventType: z.literal("subscription.paused") }),
  ),
]);

export function webhookEventEntityToJSON(
  webhookEventEntity: WebhookEventEntity,
): string {
  return JSON.stringify(
    WebhookEventEntity$outboundSchema.parse(webhookEventEntity),
  );
}
export function webhookEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEventEntity' from JSON`,
  );
}
