/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DisputeEntity,
  DisputeEntity$inboundSchema,
  DisputeEntity$Outbound,
  DisputeEntity$outboundSchema,
} from "./disputeentity.js";

/**
 * The event name.
 */
export const WebhookDisputeCreatedEventEntityEventType = {
  DisputeCreated: "dispute.created",
} as const;
/**
 * The event name.
 */
export type WebhookDisputeCreatedEventEntityEventType = ClosedEnum<
  typeof WebhookDisputeCreatedEventEntityEventType
>;

export type WebhookDisputeCreatedEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookDisputeCreatedEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: DisputeEntity;
};

/** @internal */
export const WebhookDisputeCreatedEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookDisputeCreatedEventEntityEventType> = z
    .nativeEnum(WebhookDisputeCreatedEventEntityEventType);
/** @internal */
export const WebhookDisputeCreatedEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookDisputeCreatedEventEntityEventType> =
    WebhookDisputeCreatedEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookDisputeCreatedEventEntity$inboundSchema: z.ZodType<
  WebhookDisputeCreatedEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookDisputeCreatedEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: DisputeEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookDisputeCreatedEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: DisputeEntity$Outbound;
};

/** @internal */
export const WebhookDisputeCreatedEventEntity$outboundSchema: z.ZodType<
  WebhookDisputeCreatedEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookDisputeCreatedEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookDisputeCreatedEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: DisputeEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookDisputeCreatedEventEntityToJSON(
  webhookDisputeCreatedEventEntity: WebhookDisputeCreatedEventEntity,
): string {
  return JSON.stringify(
    WebhookDisputeCreatedEventEntity$outboundSchema.parse(
      webhookDisputeCreatedEventEntity,
    ),
  );
}
export function webhookDisputeCreatedEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDisputeCreatedEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDisputeCreatedEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDisputeCreatedEventEntity' from JSON`,
  );
}
