/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookSubscriptionEntity,
  WebhookSubscriptionEntity$inboundSchema,
  WebhookSubscriptionEntity$Outbound,
  WebhookSubscriptionEntity$outboundSchema,
} from "./webhooksubscriptionentity.js";

/**
 * The event name.
 */
export const WebhookSubscriptionUnpaidEventEntityEventType = {
  SubscriptionUnpaid: "subscription.unpaid",
} as const;
/**
 * The event name.
 */
export type WebhookSubscriptionUnpaidEventEntityEventType = ClosedEnum<
  typeof WebhookSubscriptionUnpaidEventEntityEventType
>;

export type WebhookSubscriptionUnpaidEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookSubscriptionUnpaidEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: WebhookSubscriptionEntity;
};

/** @internal */
export const WebhookSubscriptionUnpaidEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionUnpaidEventEntityEventType> = z
    .nativeEnum(WebhookSubscriptionUnpaidEventEntityEventType);
/** @internal */
export const WebhookSubscriptionUnpaidEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionUnpaidEventEntityEventType> =
    WebhookSubscriptionUnpaidEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookSubscriptionUnpaidEventEntity$inboundSchema: z.ZodType<
  WebhookSubscriptionUnpaidEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionUnpaidEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: WebhookSubscriptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookSubscriptionUnpaidEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: WebhookSubscriptionEntity$Outbound;
};

/** @internal */
export const WebhookSubscriptionUnpaidEventEntity$outboundSchema: z.ZodType<
  WebhookSubscriptionUnpaidEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookSubscriptionUnpaidEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionUnpaidEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: WebhookSubscriptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookSubscriptionUnpaidEventEntityToJSON(
  webhookSubscriptionUnpaidEventEntity: WebhookSubscriptionUnpaidEventEntity,
): string {
  return JSON.stringify(
    WebhookSubscriptionUnpaidEventEntity$outboundSchema.parse(
      webhookSubscriptionUnpaidEventEntity,
    ),
  );
}
export function webhookSubscriptionUnpaidEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionUnpaidEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSubscriptionUnpaidEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionUnpaidEventEntity' from JSON`,
  );
}
