/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookSubscriptionEntity,
  WebhookSubscriptionEntity$inboundSchema,
  WebhookSubscriptionEntity$Outbound,
  WebhookSubscriptionEntity$outboundSchema,
} from "./webhooksubscriptionentity.js";

/**
 * The event name.
 */
export const WebhookSubscriptionTrialingEventEntityEventType = {
  SubscriptionTrialing: "subscription.trialing",
} as const;
/**
 * The event name.
 */
export type WebhookSubscriptionTrialingEventEntityEventType = ClosedEnum<
  typeof WebhookSubscriptionTrialingEventEntityEventType
>;

export type WebhookSubscriptionTrialingEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookSubscriptionTrialingEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: WebhookSubscriptionEntity;
};

/** @internal */
export const WebhookSubscriptionTrialingEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionTrialingEventEntityEventType> = z
    .nativeEnum(WebhookSubscriptionTrialingEventEntityEventType);
/** @internal */
export const WebhookSubscriptionTrialingEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionTrialingEventEntityEventType> =
    WebhookSubscriptionTrialingEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookSubscriptionTrialingEventEntity$inboundSchema: z.ZodType<
  WebhookSubscriptionTrialingEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionTrialingEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: WebhookSubscriptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookSubscriptionTrialingEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: WebhookSubscriptionEntity$Outbound;
};

/** @internal */
export const WebhookSubscriptionTrialingEventEntity$outboundSchema: z.ZodType<
  WebhookSubscriptionTrialingEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookSubscriptionTrialingEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionTrialingEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: WebhookSubscriptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookSubscriptionTrialingEventEntityToJSON(
  webhookSubscriptionTrialingEventEntity:
    WebhookSubscriptionTrialingEventEntity,
): string {
  return JSON.stringify(
    WebhookSubscriptionTrialingEventEntity$outboundSchema.parse(
      webhookSubscriptionTrialingEventEntity,
    ),
  );
}
export function webhookSubscriptionTrialingEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionTrialingEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSubscriptionTrialingEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionTrialingEventEntity' from JSON`,
  );
}
