/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookSubscriptionEntity,
  WebhookSubscriptionEntity$inboundSchema,
  WebhookSubscriptionEntity$Outbound,
  WebhookSubscriptionEntity$outboundSchema,
} from "./webhooksubscriptionentity.js";

/**
 * The event name.
 */
export const WebhookSubscriptionExpiredEventEntityEventType = {
  SubscriptionExpired: "subscription.expired",
} as const;
/**
 * The event name.
 */
export type WebhookSubscriptionExpiredEventEntityEventType = ClosedEnum<
  typeof WebhookSubscriptionExpiredEventEntityEventType
>;

export type WebhookSubscriptionExpiredEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookSubscriptionExpiredEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: WebhookSubscriptionEntity;
};

/** @internal */
export const WebhookSubscriptionExpiredEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionExpiredEventEntityEventType> = z
    .nativeEnum(WebhookSubscriptionExpiredEventEntityEventType);
/** @internal */
export const WebhookSubscriptionExpiredEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionExpiredEventEntityEventType> =
    WebhookSubscriptionExpiredEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookSubscriptionExpiredEventEntity$inboundSchema: z.ZodType<
  WebhookSubscriptionExpiredEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionExpiredEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: WebhookSubscriptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookSubscriptionExpiredEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: WebhookSubscriptionEntity$Outbound;
};

/** @internal */
export const WebhookSubscriptionExpiredEventEntity$outboundSchema: z.ZodType<
  WebhookSubscriptionExpiredEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookSubscriptionExpiredEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionExpiredEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: WebhookSubscriptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookSubscriptionExpiredEventEntityToJSON(
  webhookSubscriptionExpiredEventEntity: WebhookSubscriptionExpiredEventEntity,
): string {
  return JSON.stringify(
    WebhookSubscriptionExpiredEventEntity$outboundSchema.parse(
      webhookSubscriptionExpiredEventEntity,
    ),
  );
}
export function webhookSubscriptionExpiredEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionExpiredEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSubscriptionExpiredEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionExpiredEventEntity' from JSON`,
  );
}
