/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookSubscriptionEntity,
  WebhookSubscriptionEntity$inboundSchema,
  WebhookSubscriptionEntity$Outbound,
  WebhookSubscriptionEntity$outboundSchema,
} from "./webhooksubscriptionentity.js";

/**
 * The event name.
 */
export const WebhookSubscriptionPaidEventEntityEventType = {
  SubscriptionPaid: "subscription.paid",
} as const;
/**
 * The event name.
 */
export type WebhookSubscriptionPaidEventEntityEventType = ClosedEnum<
  typeof WebhookSubscriptionPaidEventEntityEventType
>;

export type WebhookSubscriptionPaidEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookSubscriptionPaidEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: WebhookSubscriptionEntity;
};

/** @internal */
export const WebhookSubscriptionPaidEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionPaidEventEntityEventType> = z
    .nativeEnum(WebhookSubscriptionPaidEventEntityEventType);
/** @internal */
export const WebhookSubscriptionPaidEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionPaidEventEntityEventType> =
    WebhookSubscriptionPaidEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookSubscriptionPaidEventEntity$inboundSchema: z.ZodType<
  WebhookSubscriptionPaidEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionPaidEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: WebhookSubscriptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookSubscriptionPaidEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: WebhookSubscriptionEntity$Outbound;
};

/** @internal */
export const WebhookSubscriptionPaidEventEntity$outboundSchema: z.ZodType<
  WebhookSubscriptionPaidEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookSubscriptionPaidEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionPaidEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: WebhookSubscriptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookSubscriptionPaidEventEntityToJSON(
  webhookSubscriptionPaidEventEntity: WebhookSubscriptionPaidEventEntity,
): string {
  return JSON.stringify(
    WebhookSubscriptionPaidEventEntity$outboundSchema.parse(
      webhookSubscriptionPaidEventEntity,
    ),
  );
}
export function webhookSubscriptionPaidEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionPaidEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSubscriptionPaidEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionPaidEventEntity' from JSON`,
  );
}
