/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CheckoutEntity,
  CheckoutEntity$inboundSchema,
  CheckoutEntity$Outbound,
  CheckoutEntity$outboundSchema,
} from "./checkoutentity.js";

/**
 * The event name.
 */
export const EventType = {
  CheckoutCompleted: "checkout.completed",
} as const;
/**
 * The event name.
 */
export type EventType = ClosedEnum<typeof EventType>;

export type WebhookCheckoutCompletedEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: EventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: CheckoutEntity;
};

/** @internal */
export const EventType$inboundSchema: z.ZodNativeEnum<typeof EventType> = z
  .nativeEnum(EventType);
/** @internal */
export const EventType$outboundSchema: z.ZodNativeEnum<typeof EventType> =
  EventType$inboundSchema;

/** @internal */
export const WebhookCheckoutCompletedEventEntity$inboundSchema: z.ZodType<
  WebhookCheckoutCompletedEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: EventType$inboundSchema,
  created_at: z.number(),
  object: CheckoutEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookCheckoutCompletedEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: CheckoutEntity$Outbound;
};

/** @internal */
export const WebhookCheckoutCompletedEventEntity$outboundSchema: z.ZodType<
  WebhookCheckoutCompletedEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookCheckoutCompletedEventEntity
> = z.object({
  id: z.string(),
  eventType: EventType$outboundSchema,
  createdAt: z.number(),
  object: CheckoutEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookCheckoutCompletedEventEntityToJSON(
  webhookCheckoutCompletedEventEntity: WebhookCheckoutCompletedEventEntity,
): string {
  return JSON.stringify(
    WebhookCheckoutCompletedEventEntity$outboundSchema.parse(
      webhookCheckoutCompletedEventEntity,
    ),
  );
}
export function webhookCheckoutCompletedEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookCheckoutCompletedEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookCheckoutCompletedEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookCheckoutCompletedEventEntity' from JSON`,
  );
}
