/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookSubscriptionEntity,
  WebhookSubscriptionEntity$inboundSchema,
  WebhookSubscriptionEntity$Outbound,
  WebhookSubscriptionEntity$outboundSchema,
} from "./webhooksubscriptionentity.js";

/**
 * The event name.
 */
export const WebhookSubscriptionPausedEventEntityEventType = {
  SubscriptionPaused: "subscription.paused",
} as const;
/**
 * The event name.
 */
export type WebhookSubscriptionPausedEventEntityEventType = ClosedEnum<
  typeof WebhookSubscriptionPausedEventEntityEventType
>;

export type WebhookSubscriptionPausedEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookSubscriptionPausedEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: WebhookSubscriptionEntity;
};

/** @internal */
export const WebhookSubscriptionPausedEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionPausedEventEntityEventType> = z
    .nativeEnum(WebhookSubscriptionPausedEventEntityEventType);
/** @internal */
export const WebhookSubscriptionPausedEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionPausedEventEntityEventType> =
    WebhookSubscriptionPausedEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookSubscriptionPausedEventEntity$inboundSchema: z.ZodType<
  WebhookSubscriptionPausedEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionPausedEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: WebhookSubscriptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookSubscriptionPausedEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: WebhookSubscriptionEntity$Outbound;
};

/** @internal */
export const WebhookSubscriptionPausedEventEntity$outboundSchema: z.ZodType<
  WebhookSubscriptionPausedEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookSubscriptionPausedEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionPausedEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: WebhookSubscriptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookSubscriptionPausedEventEntityToJSON(
  webhookSubscriptionPausedEventEntity: WebhookSubscriptionPausedEventEntity,
): string {
  return JSON.stringify(
    WebhookSubscriptionPausedEventEntity$outboundSchema.parse(
      webhookSubscriptionPausedEventEntity,
    ),
  );
}
export function webhookSubscriptionPausedEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionPausedEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSubscriptionPausedEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionPausedEventEntity' from JSON`,
  );
}
