/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RefundEntity,
  RefundEntity$inboundSchema,
  RefundEntity$Outbound,
  RefundEntity$outboundSchema,
} from "./refundentity.js";

/**
 * The event name.
 */
export const WebhookRefundCreatedEventEntityEventType = {
  RefundCreated: "refund.created",
} as const;
/**
 * The event name.
 */
export type WebhookRefundCreatedEventEntityEventType = ClosedEnum<
  typeof WebhookRefundCreatedEventEntityEventType
>;

export type WebhookRefundCreatedEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookRefundCreatedEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: RefundEntity;
};

/** @internal */
export const WebhookRefundCreatedEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookRefundCreatedEventEntityEventType> = z
    .nativeEnum(WebhookRefundCreatedEventEntityEventType);
/** @internal */
export const WebhookRefundCreatedEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookRefundCreatedEventEntityEventType> =
    WebhookRefundCreatedEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookRefundCreatedEventEntity$inboundSchema: z.ZodType<
  WebhookRefundCreatedEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookRefundCreatedEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: RefundEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookRefundCreatedEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: RefundEntity$Outbound;
};

/** @internal */
export const WebhookRefundCreatedEventEntity$outboundSchema: z.ZodType<
  WebhookRefundCreatedEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookRefundCreatedEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookRefundCreatedEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: RefundEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookRefundCreatedEventEntityToJSON(
  webhookRefundCreatedEventEntity: WebhookRefundCreatedEventEntity,
): string {
  return JSON.stringify(
    WebhookRefundCreatedEventEntity$outboundSchema.parse(
      webhookRefundCreatedEventEntity,
    ),
  );
}
export function webhookRefundCreatedEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookRefundCreatedEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookRefundCreatedEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookRefundCreatedEventEntity' from JSON`,
  );
}
