/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookSubscriptionEntity,
  WebhookSubscriptionEntity$inboundSchema,
  WebhookSubscriptionEntity$Outbound,
  WebhookSubscriptionEntity$outboundSchema,
} from "./webhooksubscriptionentity.js";

/**
 * The event name.
 */
export const WebhookSubscriptionUpdateEventEntityEventType = {
  SubscriptionUpdate: "subscription.update",
} as const;
/**
 * The event name.
 */
export type WebhookSubscriptionUpdateEventEntityEventType = ClosedEnum<
  typeof WebhookSubscriptionUpdateEventEntityEventType
>;

export type WebhookSubscriptionUpdateEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookSubscriptionUpdateEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: WebhookSubscriptionEntity;
};

/** @internal */
export const WebhookSubscriptionUpdateEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionUpdateEventEntityEventType> = z
    .nativeEnum(WebhookSubscriptionUpdateEventEntityEventType);
/** @internal */
export const WebhookSubscriptionUpdateEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionUpdateEventEntityEventType> =
    WebhookSubscriptionUpdateEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookSubscriptionUpdateEventEntity$inboundSchema: z.ZodType<
  WebhookSubscriptionUpdateEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionUpdateEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: WebhookSubscriptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookSubscriptionUpdateEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: WebhookSubscriptionEntity$Outbound;
};

/** @internal */
export const WebhookSubscriptionUpdateEventEntity$outboundSchema: z.ZodType<
  WebhookSubscriptionUpdateEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookSubscriptionUpdateEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionUpdateEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: WebhookSubscriptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookSubscriptionUpdateEventEntityToJSON(
  webhookSubscriptionUpdateEventEntity: WebhookSubscriptionUpdateEventEntity,
): string {
  return JSON.stringify(
    WebhookSubscriptionUpdateEventEntity$outboundSchema.parse(
      webhookSubscriptionUpdateEventEntity,
    ),
  );
}
export function webhookSubscriptionUpdateEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionUpdateEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSubscriptionUpdateEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionUpdateEventEntity' from JSON`,
  );
}
