/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookSubscriptionEntity,
  WebhookSubscriptionEntity$inboundSchema,
  WebhookSubscriptionEntity$Outbound,
  WebhookSubscriptionEntity$outboundSchema,
} from "./webhooksubscriptionentity.js";

/**
 * The event name.
 */
export const WebhookSubscriptionPastDueEventEntityEventType = {
  SubscriptionPastDue: "subscription.past_due",
} as const;
/**
 * The event name.
 */
export type WebhookSubscriptionPastDueEventEntityEventType = ClosedEnum<
  typeof WebhookSubscriptionPastDueEventEntityEventType
>;

export type WebhookSubscriptionPastDueEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookSubscriptionPastDueEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: WebhookSubscriptionEntity;
};

/** @internal */
export const WebhookSubscriptionPastDueEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionPastDueEventEntityEventType> = z
    .nativeEnum(WebhookSubscriptionPastDueEventEntityEventType);
/** @internal */
export const WebhookSubscriptionPastDueEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionPastDueEventEntityEventType> =
    WebhookSubscriptionPastDueEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookSubscriptionPastDueEventEntity$inboundSchema: z.ZodType<
  WebhookSubscriptionPastDueEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionPastDueEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: WebhookSubscriptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookSubscriptionPastDueEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: WebhookSubscriptionEntity$Outbound;
};

/** @internal */
export const WebhookSubscriptionPastDueEventEntity$outboundSchema: z.ZodType<
  WebhookSubscriptionPastDueEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookSubscriptionPastDueEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionPastDueEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: WebhookSubscriptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookSubscriptionPastDueEventEntityToJSON(
  webhookSubscriptionPastDueEventEntity: WebhookSubscriptionPastDueEventEntity,
): string {
  return JSON.stringify(
    WebhookSubscriptionPastDueEventEntity$outboundSchema.parse(
      webhookSubscriptionPastDueEventEntity,
    ),
  );
}
export function webhookSubscriptionPastDueEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionPastDueEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSubscriptionPastDueEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionPastDueEventEntity' from JSON`,
  );
}
