/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookSubscriptionEntity,
  WebhookSubscriptionEntity$inboundSchema,
  WebhookSubscriptionEntity$Outbound,
  WebhookSubscriptionEntity$outboundSchema,
} from "./webhooksubscriptionentity.js";

/**
 * The event name.
 */
export const WebhookSubscriptionCanceledEventEntityEventType = {
  SubscriptionCanceled: "subscription.canceled",
} as const;
/**
 * The event name.
 */
export type WebhookSubscriptionCanceledEventEntityEventType = ClosedEnum<
  typeof WebhookSubscriptionCanceledEventEntityEventType
>;

export type WebhookSubscriptionCanceledEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookSubscriptionCanceledEventEntityEventType;
  /**
   * Creation date of the event.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: WebhookSubscriptionEntity;
};

/** @internal */
export const WebhookSubscriptionCanceledEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionCanceledEventEntityEventType> = z
    .nativeEnum(WebhookSubscriptionCanceledEventEntityEventType);
/** @internal */
export const WebhookSubscriptionCanceledEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookSubscriptionCanceledEventEntityEventType> =
    WebhookSubscriptionCanceledEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookSubscriptionCanceledEventEntity$inboundSchema: z.ZodType<
  WebhookSubscriptionCanceledEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionCanceledEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: WebhookSubscriptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookSubscriptionCanceledEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: WebhookSubscriptionEntity$Outbound;
};

/** @internal */
export const WebhookSubscriptionCanceledEventEntity$outboundSchema: z.ZodType<
  WebhookSubscriptionCanceledEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookSubscriptionCanceledEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookSubscriptionCanceledEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: WebhookSubscriptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookSubscriptionCanceledEventEntityToJSON(
  webhookSubscriptionCanceledEventEntity:
    WebhookSubscriptionCanceledEventEntity,
): string {
  return JSON.stringify(
    WebhookSubscriptionCanceledEventEntity$outboundSchema.parse(
      webhookSubscriptionCanceledEventEntity,
    ),
  );
}
export function webhookSubscriptionCanceledEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionCanceledEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSubscriptionCanceledEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionCanceledEventEntity' from JSON`,
  );
}
