/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";
import { CreemError } from "./creemerror.js";

export type CustomerCreditsErrorResponseDtoData = {
  /**
   * Error details
   */
  error: components.CustomerCreditsErrorDetailDto;
};

export class CustomerCreditsErrorResponseDto extends CreemError {
  /**
   * Error details
   */
  error: components.CustomerCreditsErrorDetailDto;

  /** The original data that was passed to this error instance. */
  data$: CustomerCreditsErrorResponseDtoData;

  constructor(
    err: CustomerCreditsErrorResponseDtoData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "CustomerCreditsErrorResponseDto";
  }
}

/** @internal */
export const CustomerCreditsErrorResponseDto$inboundSchema: z.ZodType<
  CustomerCreditsErrorResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: components.CustomerCreditsErrorDetailDto$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CustomerCreditsErrorResponseDto(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CustomerCreditsErrorResponseDto$Outbound = {
  error: components.CustomerCreditsErrorDetailDto$Outbound;
};

/** @internal */
export const CustomerCreditsErrorResponseDto$outboundSchema: z.ZodType<
  CustomerCreditsErrorResponseDto$Outbound,
  z.ZodTypeDef,
  CustomerCreditsErrorResponseDto
> = z.instanceof(CustomerCreditsErrorResponseDto)
  .transform(v => v.data$)
  .pipe(z.object({
    error: components.CustomerCreditsErrorDetailDto$outboundSchema,
  }));
